spring.application.name=proyecto

# 1. URL APUNTANDO A LA CARPETA (Sin el tnsnames.ora al final)
spring.datasource.url=jdbc:oracle:thin:@adminylenguajesbasededatos_high?TNS_ADMIN=/Users/kendall/Documents/Lenguaje_de_base_de_datos/Wallet_AdminYLenguajesBaseDeDatos

# 2. Credenciales (Poné tu pass real de la DB)
spring.datasource.username=Admin
spring.datasource.password=Pepito42&siu

# 3. Configuración de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# 4. Logs
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

# Fuerza a que Spring verifique la conexión antes de usarla
spring.datasource.hikari.connection-test-query=SELECT 1 FROM DUAL
spring.datasource.hikari.validation-timeout=3000
# Evita que las conexiones viejas den problemas
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=30000