CREATE TABLE TAJO_ESTADOS_TB(
    ID_ESTADO NUMBER CONSTRAINT ESTADO_ID_PK PRIMARY KEY,
    NOMBRE_ESTADO VARCHAR2(100));
    
CREATE TABLE TAJO_MATERIALES_TB(
    ID_MATERIAL NUMBER CONSTRAINT MATERIAL_ID_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    UNIDAD_MEDIDA VARCHAR2(100),
    FUNCION VARCHAR2(1000),
    ID_ESTADO NUMBER,
CONSTRAINT MATERIAL_ESTADO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_TIPO_CLIENTE_TB(
    ID_TIPO_CLIENTE NUMBER CONSTRAINT TAJO_TIPO_CLIENTE_PK PRIMARY KEY,
    NOMBRE_TIPO_CLIENTE VARCHAR2(100),
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_TIPO_CLIENTE_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_CLIENTES_TB(
    CEDULA NUMBER CONSTRAINT TAJO_CLIENTE_PK PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    ID_TIPO_CLIENTE NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT TIPO_CLIENTE_FK FOREIGN KEY (ID_TIPO_CLIENTE)
REFERENCES TAJO_TIPO_CLIENTE_TB (ID_TIPO_CLIENTE),
CONSTRAINT ESTADO_CLIENTE_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_MAQUINARIA_TB(
    PLACA NUMBER CONSTRAINT TAJO_MAQUINARIA_PK PRIMARY KEY,
    MODELO NUMBER,
    HORAS_TRABAJADAS NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_MAQUINARIA_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_TIPO_MAQUINARIA_TB (
    PLACA NUMBER,
    ID_TIPO_MAQUINARIA NUMBER,
    DESCRIPCION VARCHAR2(1000),
    ID_ESTADO NUMBER,
CONSTRAINT TAJO_TIPO_MAQUINARIA_PK PRIMARY KEY (PLACA, ID_TIPO_MAQUINARIA),
CONSTRAINT ESTADO_TIPO_MAQUINARIA_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_TURNOS_TB (
    ID_TURNO NUMBER CONSTRAINT TAJO_TURNOS_ID_PK PRIMARY KEY,
    NOMBRE_TURNO VARCHAR2(100),
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_TURNO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_USUARIOS_TB(
    IDENTIFICACION NUMBER CONSTRAINT TAJO_USUARIOS_PK PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR2(100),
    APELLIDO_PATERNO VARCHAR2(100),
    APELLIDO_MATERNO VARCHAR2(100),
    EDAD NUMBER,
    FECHA_INGRESO DATE,
    ID_TURNO NUMBER,
    PLACA NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT TURNO_USUARIO_FK FOREIGN KEY (ID_TURNO)
REFERENCES TAJO_TURNOS_TB (ID_TURNO),
CONSTRAINT PLACA_USUARIO_FK FOREIGN KEY (PLACA)
REFERENCES TAJO_MAQUINARIA_TB (PLACA),
CONSTRAINT ESTADO_USUARIO_FK FOREIGN KEY(ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_CORREOS_TB (
    IDENTIFICACION NUMBER,
    CORREO VARCHAR2(100),
    ID_ESTADO NUMBER,
CONSTRAINT TAJO_CORREOS_PK PRIMARY KEY (IDENTIFICACION, CORREO),
CONSTRAINT ESTADO_CORREO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_TELEFONOS_TB (
    IDENTIFICACION NUMBER,
    TELEFONO NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT TAJO_TELEFONOS_PK PRIMARY KEY (IDENTIFICACION, TELEFONO),
CONSTRAINT ESTADO_TELEFONO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_ROLES_TB(
    IDENTIFICACION NUMBER,
    ID_ROL NUMBER,
    NOMBRE_ROL VARCHAR2(100),
    ID_ESTADO NUMBER,
CONSTRAINT TAJO_ROLES_PK PRIMARY KEY (IDENTIFICACION, ID_ROL),
CONSTRAINT ESTADO_ROL_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));


-----

CREATE TABLE TAJO_EXTRACCIONES_TB (
    ID_EXTRACCION NUMBER CONSTRAINT TAJO_EXTRACCION_PK PRIMARY KEY,
    IDENTIFICACION NUMBER,
    ID_MATERIAL NUMBER,
    FECHA_EXTRACCION DATE,
    ID_ESTADO NUMBER,
CONSTRAINT USUARIO_EXTRACCION_FK FOREIGN KEY (IDENTIFICACION)
REFERENCES TAJO_USUARIOS_TB (IDENTIFICACION),
CONSTRAINT MATERIAL_EXTRACCION_FK FOREIGN KEY (ID_MATERIAL)
REFERENCES TAJO_MATERIALES_TB (ID_MATERIAL),
CONSTRAINT ESTADO_EXTRACCION_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

---

CREATE TABLE TAJO_MAQUINARIA_EXTRACCION_TB(
    PLACA NUMBER,
    ID_EXTRACCION NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT TAJO_MAQUINARIA_EXTRACCION_PK PRIMARY KEY (PLACA, ID_EXTRACCION),
CONSTRAINT TAJO_MAQUINARIA_EXTRACCION_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_MANTENIMIENTO_TB (
    ID_MANTENIMIENTO NUMBER CONSTRAINT TAJO_MANTENIMIENTO_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(1000),
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_MANTENIMIENTO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_MAQUINARIA_MANTENIMIENTO_TB(
    PLACA NUMBER,
    ID_MANTENIMIENTO NUMBER,
    FECHA_MANTENIMIENTO DATE,
    ID_ESTADO NUMBER,
CONSTRAINT TAJO_MAQUINARIA_MANTENIMIENTO_PK PRIMARY KEY (PLACA, ID_MANTENIMIENTO),
CONSTRAINT ESTADO_MAQUINARIA_MANTE_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_PLANILLAS_TB(
    ID_PLANILLA NUMBER CONSTRAINT TAJO_PLANILLA_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(1000),
    FECHA_INICIO DATE,
    FECHA_FINAL DATE,
    FECHA_PAGO DATE,
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_PLANILLA_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_DEDUCCIONES_TB(
    ID_DEDUCCION NUMBER CONSTRAINT TAJO_DEDUCCION_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PORCENTAJE NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_DEDUCCION_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_BONIFICACIONES_TB(
    ID_BONIFICACION NUMBER CONSTRAINT TAJO_BONIFICACION_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PORCENTAJE NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_BONIFICACION_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_PAGOS_USUARIOS_TB (
    ID_PAGO  NUMBER CONSTRAINT TAJO_PAGOS_USUARIOS_PK PRIMARY KEY,
    ID_PLANILLA  NUMBER, 
    IDENTIFICACION  NUMBER,
    SALARIO_BASE NUMBER(12,2), 
    ID_DEDUCCION  NUMBER(12,2), 
    ID_BONIFICACION NUMBER(12,2), 
    SALARIO_NETO NUMBER(12,2), 
    ID_ESTADO   NUMBER,
CONSTRAINT PAGO_PLANILLA_FK FOREIGN KEY (ID_PLANILLA) 
REFERENCES TAJO_PLANILLAS_TB (ID_PLANILLA),
CONSTRAINT PAGO_USUARIO_FK FOREIGN KEY (IDENTIFICACION) 
REFERENCES TAJO_USUARIOS_TB (IDENTIFICACION),
CONSTRAINT DEDUCCION_USUARIO_FK FOREIGN KEY (ID_DEDUCCION)
REFERENCES TAJO_DEDUCCIONES_TB (ID_DEDUCCION),
CONSTRAINT BONIFICACION_USUARIO_FK FOREIGN KEY (ID_BONIFICACION)
REFERENCES TAJO_BONIFICACIONES_TB (ID_BONIFICACION));

CREATE TABLE TAJO_CONTROL_TRANSPORTE_TB(
    ID_TRANSPORTE NUMBER CONSTRAINT TAJO_TRANSPORTE_PK PRIMARY KEY,
    PLACA NUMBER,
    IDENTIFICACION NUMBER,
    ID_MATERIAL NUMBER,
    CANTIDAD_TRANSPORTADA NUMBER,
    PRECIO_TRANSPORTE NUMBER,
    DESTINO VARCHAR2(2000),
    ID_ESTADO NUMBER,
CONSTRAINT TRANSPORTE_PLACA_FK FOREIGN KEY (PLACA)
REFERENCES TAJO_MAQUINARIA_TB (PLACA),
CONSTRAINT TRANSPORTE_IDENTIFICACION_FK FOREIGN KEY (IDENTIFICACION)
REFERENCES TAJO_USUARIOS_TB (IDENTIFICACION),
CONSTRAINT TRANSPORTE_MATERIAL_FK FOREIGN KEY (ID_MATERIAL)
REFERENCES TAJO_MATERIALES_TB (ID_MATERIAL),
CONSTRAINT ESTADO_TRANSPORTE_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_PRODUCCION_TB (
    ID_PRODUCCION  NUMBER,
    ID_MATERIAL  NUMBER,
    CANTIDAD NUMBER(12,2),
    FECHA_PRODUCCION DATE DEFAULT SYSDATE,
    ID_ESTADO NUMBER,
CONSTRAINT TAJO_PRODUCCION_PK PRIMARY KEY (ID_PRODUCCION, ID_MATERIAL),
CONSTRAINT PRODUCCION_MATERIAL_FK FOREIGN KEY (ID_MATERIAL) 
REFERENCES TAJO_MATERIALES_TB (ID_MATERIAL),
CONSTRAINT FK_PROD_EST_REF FOREIGN KEY (ID_ESTADO) 
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB(
    ID_TIPO_MOVIMIENTO_INVENTARIO NUMBER CONSTRAINT TAJO_TIPO_MOVIMIENTO_PK PRIMARY KEY,
    DESCRIPCION VARCHAR2(1000),
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_TIPO_MOVIMIENTO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_INVENTARIO_TB(
    ID_INVENTARIO NUMBER,
    ID_MATERIAL NUMBER,
    CANTIDAD_MATERIAL NUMBER,
    NIVEL_STOCK VARCHAR2(100),
    ID_TIPO_MOVIMIENTO_INVENTARIO NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT TAJO_INVENTARIO_PK PRIMARY KEY (ID_INVENTARIO, ID_MATERIAL),
CONSTRAINT INVENTARIO_TIPO_MOVIMIENTO_FK FOREIGN KEY (ID_TIPO_MOVIMIENTO_INVENTARIO)
REFERENCES TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB (ID_TIPO_MOVIMIENTO_INVENTARIO),
CONSTRAINT ESTADO_INVENTARIO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));
    
CREATE TABLE TAJO_VENTAS_TB (
    ID_VENTA NUMBER CONSTRAINT TAJO_VENTA_PK PRIMARY KEY,
    CEDULA NUMBER,
    CANTIDAD_VENTA NUMBER,
    PRECIO NUMBER,
    FECHA_VENTA DATE,
    ID_ESTADO NUMBER,
CONSTRAINT CLIENTE_VENTA_FK FOREIGN KEY (CEDULA)
REFERENCES TAJO_CLIENTES_TB (CEDULA),
CONSTRAINT ESTADO_VENTA_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

ALTER TABLE TAJO_PROYECTO.TAJO_VENTAS_TB 
ADD ID_MATERIAL NUMBER;

ALTER TABLE TAJO_PROYECTO.TAJO_VENTAS_TB
ADD CONSTRAINT FK_VENTA_MATERIAL
FOREIGN KEY (ID_MATERIAL) 
REFERENCES TAJO_PROYECTO.TAJO_MATERIALES_TB(ID_MATERIAL);

CREATE TABLE TAJO_METODO_PAGO_TB (  
    ID_METODO_PAGO NUMBER CONSTRAINT TAJO_METODO_PAGO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_MEOTODO_PAGO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_DETALLE_VENTAS_TB(
    ID_VENTA NUMBER,
    ID_MATERIAL NUMBER,
    PRECIO_TOTAL NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT TAJO_DETALLE_VENTA_PK PRIMARY KEY (ID_VENTA, ID_MATERIAL),
CONSTRAINT ESTADO_DETALLE_VENTA_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_DESCUENTOS_TB (
    ID_DESCUENTO NUMBER CONSTRAINT TAJO_DESCUENTO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PORCENTAJE NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_DESCUENTO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

CREATE TABLE TAJO_IMPUESTOS_TB( 
    ID_IMPUESTO NUMBER CONSTRAINT TAJO_IMPUESTO_PK PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    PORCENTAJE NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT ESTADO_IMPUESTO_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));
    
    
CREATE TABLE TAJO_FACTURACION_TB (
    ID_FACTURA NUMBER CONSTRAINT TAJO_FACTURA_PK PRIMARY KEY,
    CEDULA NUMBER,
    ID_VENTA NUMBER,
    ID_IMPUESTO NUMBER,
    ID_DESCUENTO NUMBER,
    ID_METODO_PAGO NUMBER,
    FECHA_EMISION DATE,
    MONTO_TOTAL NUMBER,
    ID_ESTADO NUMBER,
CONSTRAINT CLIENTE_FACTURA_FK FOREIGN KEY (CEDULA)
REFERENCES TAJO_CLIENTES_TB (CEDULA),
CONSTRAINT VENTA_FACTURA_FK FOREIGN KEY (ID_VENTA)
REFERENCES TAJO_VENTAS_TB (ID_VENTA),
CONSTRAINT IMPUESTO_FACTURA_FK FOREIGN KEY (ID_IMPUESTO)
REFERENCES TAJO_IMPUESTOS_TB (ID_IMPUESTO),
CONSTRAINT DESCUENTO_FACTURA_FK FOREIGN KEY (ID_DESCUENTO)
REFERENCES TAJO_DESCUENTOS_TB (ID_DESCUENTO),
CONSTRAINT METODO_PAGO_FACTURA_FK FOREIGN KEY (ID_METODO_PAGO)
REFERENCES TAJO_METODO_PAGO_TB (ID_METODO_PAGO),
CONSTRAINT ESTADO_FACTURA_FK FOREIGN KEY (ID_ESTADO)
REFERENCES TAJO_ESTADOS_TB (ID_ESTADO));

ALTER TABLE TAJO_CLIENTES_TB
ADD CONTRASENA VARCHAR(100);


ALTER TABLE TAJO_USUARIOS_TB
ADD CONTRASENA VARCHAR(100);

---VISTAS -----

---CLIENTES---
CREATE OR REPLACE VIEW TAJO_CLIENTES_V AS
SELECT  C.CEDULA AS "CEDULA",
        C.NOMBRE_CLIENTE || ' ' || C.APELLIDO_PATERNO || ' ' || C.APELLIDO_MATERNO AS "NOMBRE COMPLETO",
        T.NOMBRE_TIPO_CLIENTE AS "TIPO CLIENTE",
        E.NOMBRE_ESTADO AS "ESTADO"
FROM TAJO_CLIENTES_TB C,
     TAJO_TIPO_CLIENTE_TB T,
     TAJO_ESTADOS_TB E
WHERE C.ID_TIPO_CLIENTE = T.ID_TIPO_CLIENTE
AND C.ID_ESTADO = E.ID_ESTADO
ORDER BY C.CEDULA ASC;

SELECT * FROM TAJO_CLIENTES_V;
/


---USUARIOS---
CREATE OR REPLACE VIEW TAJO_USUARIOS_V AS
SELECT  U.IDENTIFICACION AS "IDENTIFICACION",
        U.NOMBRE_USUARIO || ' ' || U.APELLIDO_PATERNO || ' ' || U.APELLIDO_MATERNO AS "NOMBRE COMPLETO",
        U.EDAD AS "EDAD",
        U.FECHA_INGRESO AS "FECHA INGRESO",
        T.NOMBRE_TURNO AS "TURNO",
        M.PLACA AS "MAQUINARIA ASIGNADA",
        E.NOMBRE_ESTADO AS "ESTADO"
FROM TAJO_USUARIOS_TB U,
     TAJO_TURNOS_TB T,
     TAJO_MAQUINARIA_TB M,
     TAJO_ESTADOS_TB E
WHERE U.ID_TURNO = T.ID_TURNO
AND U.PLACA = M.PLACA
AND U.ID_ESTADO = E.ID_ESTADO
ORDER BY U.IDENTIFICACION ASC;

SELECT * FROM TAJO_USUARIOS_V;
/

---MATERIALES---
CREATE OR REPLACE VIEW TAJO_MATERIALES_V AS
SELECT  M.ID_MATERIAL AS "ID MATERIAL",
        M.NOMBRE AS "MATERIAL",
        M.UNIDAD_MEDIDA AS "UNIDAD MEDIDA",
        M.FUNCION AS "FUNCION",
        E.NOMBRE_ESTADO AS "ESTADO"
FROM TAJO_MATERIALES_TB M,
     TAJO_ESTADOS_TB E
WHERE M.ID_ESTADO = E.ID_ESTADO
ORDER BY M.ID_MATERIAL ASC;

SELECT * FROM TAJO_MATERIALES_V;
/

---MAQUINARIA---
CREATE OR REPLACE VIEW TAJO_MAQUINARIA_V AS
SELECT  M.PLACA AS "PLACA",
        M.MODELO AS "MODELO",
        M.HORAS_TRABAJADAS AS "HORAS TRABAJADAS",
        E.NOMBRE_ESTADO AS "ESTADO"
FROM TAJO_MAQUINARIA_TB M,
     TAJO_ESTADOS_TB E
WHERE M.ID_ESTADO = E.ID_ESTADO
ORDER BY M.PLACA ASC;

SELECT * FROM TAJO_MAQUINARIA_V;
/

---EXTRACCIONES---
CREATE OR REPLACE VIEW TAJO_EXTRACCIONES_V AS
SELECT  EX.ID_EXTRACCION AS "ID EXTRACCION",
        U.NOMBRE_USUARIO || ' ' || U.APELLIDO_PATERNO AS "USUARIO",
        M.NOMBRE AS "MATERIAL",
        EX.FECHA_EXTRACCION AS "FECHA EXTRACCION",
        E.NOMBRE_ESTADO AS "ESTADO"
FROM TAJO_EXTRACCIONES_TB EX,
     TAJO_USUARIOS_TB U,
     TAJO_MATERIALES_TB M,
     TAJO_ESTADOS_TB E
WHERE EX.IDENTIFICACION = U.IDENTIFICACION
AND EX.ID_MATERIAL = M.ID_MATERIAL
AND EX.ID_ESTADO = E.ID_ESTADO
ORDER BY EX.ID_EXTRACCION ASC;

SELECT * FROM TAJO_EXTRACCIONES_V;
/

---PRODUCCION---
CREATE OR REPLACE VIEW TAJO_PRODUCCION_V AS
SELECT  P.ID_PRODUCCION AS "ID PRODUCCION",
        M.NOMBRE AS "MATERIAL",
        P.CANTIDAD AS "CANTIDAD",
        P.FECHA_PRODUCCION AS "FECHA PRODUCCION",
        E.NOMBRE_ESTADO AS "ESTADO"
FROM TAJO_PRODUCCION_TB P,
     TAJO_MATERIALES_TB M,
     TAJO_ESTADOS_TB E
WHERE P.ID_MATERIAL = M.ID_MATERIAL
AND P.ID_ESTADO = E.ID_ESTADO
ORDER BY P.ID_PRODUCCION ASC;

SELECT * FROM TAJO_PRODUCCION_V;
/

---VENTAS---
CREATE OR REPLACE VIEW TAJO_VENTAS_V AS
SELECT  V.ID_VENTA AS "ID VENTA",
        C.NOMBRE_CLIENTE || ' ' || C.APELLIDO_PATERNO AS "CLIENTE",
        V.CANTIDAD_VENTA AS "CANTIDAD",
        V.PRECIO AS "PRECIO",
        V.FECHA_VENTA AS "FECHA VENTA",
        E.NOMBRE_ESTADO AS "ESTADO"
FROM TAJO_VENTAS_TB V,
     TAJO_CLIENTES_TB C,
     TAJO_ESTADOS_TB E
WHERE V.CEDULA = C.CEDULA
AND V.ID_ESTADO = E.ID_ESTADO
ORDER BY V.ID_VENTA ASC;

SELECT * FROM TAJO_VENTAS_V;
/

---FACTURA---
CREATE OR REPLACE VIEW TAJO_RESUMEN_FACTURACION_V AS
SELECT F.ID_FACTURA AS "NUMERO FACTURA",
       C.NOMBRE_CLIENTE || ' ' || C.APELLIDO_PATERNO AS "CLIENTE",
       F.ID_VENTA AS "VENTA ASOCIADA",
       F.FECHA_EMISION AS "FECHA EMISION",
       F.MONTO_TOTAL AS "MONTO TOTAL",
       MP.NOMBRE AS "METODO PAGO",
       I.NOMBRE AS "IMPUESTO",
       D.NOMBRE AS "DESCUENTO",
       E.NOMBRE_ESTADO AS "ESTADO FACTURA"
FROM TAJO_FACTURACION_TB F,
     TAJO_CLIENTES_TB C,
     TAJO_METODO_PAGO_TB MP,
     TAJO_IMPUESTOS_TB I,
     TAJO_DESCUENTOS_TB D,
     TAJO_ESTADOS_TB E
WHERE F.CEDULA = C.CEDULA
AND F.ID_METODO_PAGO = MP.ID_METODO_PAGO
AND F.ID_IMPUESTO = I.ID_IMPUESTO
AND F.ID_DESCUENTO = D.ID_DESCUENTO
AND F.ID_ESTADO = E.ID_ESTADO
ORDER BY F.ID_FACTURA ASC;

SELECT * FROM TAJO_RESUMEN_FACTURACION_V;
/


---VISTAS MATERIALIZADAS---

---PRODUCCION--
CREATE MATERIALIZED VIEW TAJO_PRODUCCION_MATERIAL_VM
BUILD IMMEDIATE
REFRESH COMPLETE
AS
SELECT  M.NOMBRE AS "MATERIAL",
        SUM(P.CANTIDAD) AS "TOTAL PRODUCIDO"
FROM TAJO_PRODUCCION_TB P,
     TAJO_MATERIALES_TB M
WHERE P.ID_MATERIAL = M.ID_MATERIAL
GROUP BY M.NOMBRE;


---VENTAS---
CREATE MATERIALIZED VIEW TAJO_VENTAS_CLIENTE_VM
BUILD IMMEDIATE
REFRESH COMPLETE
AS
SELECT  C.NOMBRE_CLIENTE || ' ' || C.APELLIDO_PATERNO AS "CLIENTE",
        SUM(V.CANTIDAD_VENTA * V.PRECIO) AS "TOTAL COMPRADO"
FROM TAJO_VENTAS_TB V,
     TAJO_CLIENTES_TB C
WHERE V.CEDULA = C.CEDULA
GROUP BY C.NOMBRE_CLIENTE, C.APELLIDO_PATERNO;



    




