create or replace PACKAGE TAJO_PROYECTO_FINAL_PKG AS

----FUNCIONES-----

FUNCTION TAJO_USUARIOS_VALIDAR_ACCESO_FN (
    P_IDENTIFICACION IN TAJO_USUARIOS_TB.IDENTIFICACION%TYPE,
    P_CONTRASENA IN TAJO_USUARIOS_TB.CONTRASENA%TYPE
) RETURN NUMBER;

----
FUNCTION TAJO_USUARIOS_OBTENER_NOMBRE_COMPLETO_FN (
    P_IDENTIFICACION IN TAJO_USUARIOS_TB.IDENTIFICACION%TYPE
) RETURN VARCHAR2;

----
FUNCTION TAJO_TURNOS_USUARIOS_CONTAR_FN (
    P_ID_TURNO IN TAJO_TURNOS_TB.ID_TURNO%TYPE
) RETURN NUMBER;

-----
FUNCTION TAJO_VENTAS_TOTAL_CLIENTE_FN (
    P_CEDULA IN TAJO_CLIENTES_TB.CEDULA%TYPE
) RETURN NUMBER;

-----
FUNCTION TAJO_INVENTARIO_STOCK_ACTUAL_MATERIAL_FN (
    P_ID_MATERIAL IN TAJO_INVENTARIO_TB.ID_MATERIAL%TYPE
) RETURN NUMBER;

-----
FUNCTION TAJO_MAQUINARIA_ACTIVA_CONTAR_FN 
RETURN NUMBER;

-----
FUNCTION TAJO_FACTURACION_MONTO_TOTAL_FN (
    P_CEDULA IN TAJO_FACTURACION_TB.CEDULA%TYPE
) RETURN NUMBER;

----
FUNCTION TAJO_MAQUINARIA_HORAS_TOTALES_FN RETURN NUMBER;

----
FUNCTION TAJO_TRANSPORTE_CANTIDAD_MATERIAL_FN (
    P_ID_MATERIAL IN TAJO_CONTROL_TRANSPORTE_TB.ID_MATERIAL%TYPE
) RETURN NUMBER;

----
FUNCTION TAJO_DEDUCCIONES_PORCENTAJE_TOTAL_FN RETURN NUMBER;

----
FUNCTION TAJO_PRODUCCION_FECHA_ESPECIFICA_FN (
    P_FECHA IN DATE
) RETURN NUMBER;

----
FUNCTION TAJO_PLANILLAS_TOTAL_PAGADO_FN RETURN NUMBER;

----
FUNCTION TAJO_FACTURACION_CALCULO_IVA_FN (
    P_ID_FACTURA IN TAJO_FACTURACION_TB.ID_FACTURA%TYPE
) RETURN NUMBER;

----
FUNCTION TAJO_MAQUINARIA_CONTAR_MANTENIMIENTOS_FN (
    P_PLACA IN TAJO_MAQUINARIA_MANTENIMIENTO_TB.PLACA%TYPE
) RETURN NUMBER;

----
FUNCTION TAJO_CLIENTES_CONTAR_POR_TIPO_FN (
    P_ID_TIPO IN TAJO_CLIENTES_TB.ID_TIPO_CLIENTE%TYPE
) RETURN NUMBER;

-----
FUNCTION TAJO_USUARIOS_FECHA_INGRESO_FN (
    P_ID IN TAJO_USUARIOS_TB.IDENTIFICACION%TYPE
) RETURN DATE;


----PROCEDIMIENTOS ALMACENADOS-----

----PROCEDIMIENTOS DE BONIFICACIONES

PROCEDURE TAJO_BONIFICACIONES_INSERTAR_SP (
    P_ID_BONIFICACION IN TAJO_BONIFICACIONES_TB.ID_BONIFICACION%TYPE,
    P_NOMBRE IN TAJO_BONIFICACIONES_TB.NOMBRE%TYPE,
    P_PORCENTAJE IN TAJO_BONIFICACIONES_TB.PORCENTAJE%TYPE,
    P_ID_ESTADO IN TAJO_BONIFICACIONES_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_BONIFICACIONES_MODIFICAR_SP (
    P_ID_BONIFICACION IN TAJO_BONIFICACIONES_TB.ID_BONIFICACION%TYPE,
    P_NOMBRE_NUEVO IN TAJO_BONIFICACIONES_TB.NOMBRE%TYPE,
    P_PORCENTAJE_NUEVO IN TAJO_BONIFICACIONES_TB.PORCENTAJE%TYPE
);

PROCEDURE TAJO_BONIFICACIONES_ELIMINAR_SP (
    P_ID_BONIFICACION IN TAJO_BONIFICACIONES_TB.ID_BONIFICACION%TYPE
);

-----PROCEDIMIENTOS DE CLIENTES
PROCEDURE TAJO_CLIENTES_INSERTAR_SP (
    P_CEDULA IN TAJO_CLIENTES_TB.CEDULA%TYPE,
    P_NOMBRE_CLIENTE IN TAJO_CLIENTES_TB.NOMBRE_CLIENTE%TYPE,
    P_APELLIDO_PATERNO IN TAJO_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN TAJO_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
    P_ID_TIPO_CLIENTE IN TAJO_CLIENTES_TB.ID_TIPO_CLIENTE%TYPE,
    P_CONTRASENA IN TAJO_CLIENTES_TB.CONTRASENA%TYPE,
    P_ID_ESTADO IN TAJO_CLIENTES_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_CLIENTES_MODIFICAR_SP (
    P_CEDULA IN TAJO_CLIENTES_TB.CEDULA%TYPE,
    P_NOMBRE_CLIENTE_NUEVO IN TAJO_CLIENTES_TB.NOMBRE_CLIENTE%TYPE,
    P_APELLIDO_PATERNO_NUEVO IN TAJO_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO_NUEVO IN TAJO_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
    P_ID_TIPO_CLIENTE_NUEVO IN TAJO_CLIENTES_TB.ID_TIPO_CLIENTE%TYPE
);

PROCEDURE TAJO_CLIENTES_ELIMINAR_SP (
    P_CEDULA IN TAJO_CLIENTES_TB.CEDULA%TYPE
);

---PROCEDIMIENTOS DE CONTROL DE TRANSPORTE
PROCEDURE TAJO_TRANSPORTE_INSERTAR_SP (
    P_ID_TRANSPORTE IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_TRANSPORTE%TYPE,
    P_PLACA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.PLACA%TYPE,
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.IDENTIFICACION%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD_TRANSPORTADA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.CANTIDAD_TRANSPORTADA%TYPE,
    P_PRECIO_TRANSPORTE IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.PRECIO_TRANSPORTE%TYPE,
    P_DESTINO IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.DESTINO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_TRANSPORTE_MODIFICAR_SP (
    P_ID_TRANSPORTE IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_TRANSPORTE%TYPE,
    P_PLACA_NUEVA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.PLACA%TYPE,
    P_IDENTIFICACION_NUEVA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.IDENTIFICACION%TYPE,
    P_CANTIDAD_NUEVA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.CANTIDAD_TRANSPORTADA%TYPE,
    P_PRECIO_NUEVO IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.PRECIO_TRANSPORTE%TYPE,
    P_DESTINO_NUEVO IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.DESTINO%TYPE
);

PROCEDURE TAJO_TRANSPORTE_ELIMINAR_SP (
    P_ID_TRANSPORTE IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_TRANSPORTE%TYPE
);


----PROCEDIMIENTOS DE CORREOS
PROCEDURE TAJO_CORREOS_INSERTAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_CORREOS_TB.IDENTIFICACION%TYPE,
    P_CORREO IN TAJO_PROYECTO.TAJO_CORREOS_TB.CORREO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_CORREOS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_CORREOS_MODIFICAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_CORREOS_TB.IDENTIFICACION%TYPE,
    P_CORREO_NUEVO IN TAJO_PROYECTO.TAJO_CORREOS_TB.CORREO%TYPE
);

PROCEDURE TAJO_CORREOS_ELIMINAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_CORREOS_TB.IDENTIFICACION%TYPE
);

----PROCEDIMIENTOS DE DEDUCCIONES
PROCEDURE TAJO_DEDUCCIONES_INSERTAR_SP (
    P_ID_DEDUCCION IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.ID_DEDUCCION%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.NOMBRE%TYPE,
    P_PORCENTAJE IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.PORCENTAJE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_DEDUCCIONES_MODIFICAR_SP (
    P_ID_DEDUCCION IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.ID_DEDUCCION%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.NOMBRE%TYPE,
    P_PORCENTAJE_NUEVO IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.PORCENTAJE%TYPE
);

PROCEDURE TAJO_DEDUCCIONES_ELIMINAR_SP (
    P_ID_DEDUCCION IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.ID_DEDUCCION%TYPE
);

----PROCEDIMIENTOS DE DESCUENTOS
PROCEDURE TAJO_DESCUENTOS_INSERTAR_SP (
    P_ID_DESCUENTO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.ID_DESCUENTO%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.NOMBRE%TYPE,
    P_PORCENTAJE IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.PORCENTAJE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_DESCUENTOS_MODIFICAR_SP (
    P_ID_DESCUENTO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.ID_DESCUENTO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.NOMBRE%TYPE,
    P_PORCENTAJE_NUEVO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.PORCENTAJE%TYPE
);

PROCEDURE TAJO_DESCUENTOS_ELIMINAR_SP (
    P_ID_DESCUENTO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.ID_DESCUENTO%TYPE
);

PROCEDURE TAJO_DETALLE_VENTAS_INSERTAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_VENTA%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_MATERIAL%TYPE,
    P_PRECIO_TOTAL IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.PRECIO_TOTAL%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_DETALLE_VENTAS_MODIFICAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_VENTA%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_MATERIAL%TYPE,
    P_PRECIO_NUEVO IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.PRECIO_TOTAL%TYPE
);

PROCEDURE TAJO_DETALLE_VENTAS_ELIMINAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_VENTA%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_MATERIAL%TYPE
);

---PROCEDIMIENTOS DE ESTADOS
PROCEDURE TAJO_ESTADOS_INSERTAR_SP (
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.ID_ESTADO%TYPE,
    P_NOMBRE_ESTADO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.NOMBRE_ESTADO%TYPE
);

PROCEDURE TAJO_ESTADOS_MODIFICAR_SP (
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.ID_ESTADO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.NOMBRE_ESTADO%TYPE
);

PROCEDURE TAJO_ESTADOS_ELIMINAR_SP (
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.ID_ESTADO%TYPE
);

----PROCEDIMIENTOS DE EXTRACCIONES
PROCEDURE TAJO_EXTRACCIONES_INSERTAR_SP (
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_EXTRACCION%TYPE,
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.IDENTIFICACION%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_MATERIAL%TYPE,
    P_FECHA_EXTRACCION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.FECHA_EXTRACCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_EXTRACCIONES_MODIFICAR_SP (
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_EXTRACCION%TYPE,
    P_IDENTIFICACION_NUEVA IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.IDENTIFICACION%TYPE,
    P_ID_MATERIAL_NUEVO IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_MATERIAL%TYPE,
    P_FECHA_NUEVA IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.FECHA_EXTRACCION%TYPE,
    P_ID_ESTADO_NUEVO IN NUMBER
);

PROCEDURE TAJO_EXTRACCIONES_ELIMINAR_SP (
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_EXTRACCION%TYPE
);

----PROCEDIMIENTOS DE FACTURACION
PROCEDURE TAJO_FACTURACION_INSERTAR_SP (
    P_ID_FACTURA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_FACTURA%TYPE,
    P_CEDULA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.CEDULA%TYPE,
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_VENTA%TYPE,
    P_ID_IMPUESTO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_IMPUESTO%TYPE,
    P_ID_DESCUENTO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_DESCUENTO%TYPE,
    P_ID_METODO_PAGO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_METODO_PAGO%TYPE,
    P_FECHA_EMISION IN TAJO_PROYECTO.TAJO_FACTURACION_TB.FECHA_EMISION%TYPE,
    P_MONTO_TOTAL IN TAJO_PROYECTO.TAJO_FACTURACION_TB.MONTO_TOTAL%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_FACTURACION_MODIFICAR_SP (
    P_ID_FACTURA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_FACTURA%TYPE,
    P_ID_METODO_PAGO_NUEVO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_METODO_PAGO%TYPE,
    P_MONTO_NUEVO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.MONTO_TOTAL%TYPE
);

PROCEDURE TAJO_FACTURACION_ELIMINAR_SP (
    P_ID_FACTURA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_FACTURA%TYPE
);

----PROCEDIMIENTOS DE IMPUESTOS
PROCEDURE TAJO_IMPUESTOS_INSERTAR_SP (
    P_ID_IMPUESTO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.ID_IMPUESTO%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.NOMBRE%TYPE,
    P_PORCENTAJE IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.PORCENTAJE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_IMPUESTOS_MODIFICAR_SP (
    P_ID_IMPUESTO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.ID_IMPUESTO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.NOMBRE%TYPE,
    P_PORCENTAJE_NUEVO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.PORCENTAJE%TYPE
);

PROCEDURE TAJO_IMPUESTOS_ELIMINAR_SP (
    P_ID_IMPUESTO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.ID_IMPUESTO%TYPE
);

----PROCEDIMIENTOS DE INVENTARIO
PROCEDURE TAJO_INVENTARIO_INSERTAR_SP (
    P_ID_INVENTARIO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_INVENTARIO%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.CANTIDAD_MATERIAL%TYPE,
    P_NIVEL_STOCK IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.NIVEL_STOCK%TYPE,
    P_ID_TIPO_MOV IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO_INVENTARIO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_INVENTARIO_MODIFICAR_SP (
    P_ID_INVENTARIO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_INVENTARIO%TYPE,
    P_CANTIDAD_NUEVA IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.CANTIDAD_MATERIAL%TYPE,
    P_STOCK_NUEVO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.NIVEL_STOCK%TYPE
);

PROCEDURE TAJO_INVENTARIO_ELIMINAR_SP (
    P_ID_INVENTARIO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_INVENTARIO%TYPE,
    P_ID_MATERIAL   IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_MATERIAL%TYPE
);

---PROCEDIMIENTOS DE LA TABLA MANTENIMIENTOS
PROCEDURE TAJO_MANTENIMIENTO_INSERTAR_SP (
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_DESCRIPCION IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_MANTENIMIENTO_MODIFICAR_SP (
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_DESCRIPCION_NUEVA IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.DESCRIPCION%TYPE
);

PROCEDURE TAJO_MANTENIMIENTO_ELIMINAR_SP (
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE
);

----PROCEDIMIENTOS DE LA TABLA DE TAJO_MAQUINARIA_EXTRACCIONES_TB
PROCEDURE TAJO_MAQUINARIA_EXTRACCION_INSERTAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.PLACA%TYPE,
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_EXTRACCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_MAQUINARIA_EXTRACCION_MODIFICAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.PLACA%TYPE,
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_EXTRACCION%TYPE,
    P_ID_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_MAQUINARIA_EXTRACCION_ELIMINAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.PLACA%TYPE,
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_EXTRACCION%TYPE
);

----PROCEDIMIENTOS DE LA TABLA TAJO_MAQUINARIA_MANTENIMIENTO_TB
PROCEDURE TAJO_MAQUINARIA_MANTENIMIENTO_INSERTAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.PLACA%TYPE,
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_FECHA_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.FECHA_MANTENIMIENTO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_MAQUINARIA_MANTENIMIENTO_MODIFICAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.PLACA%TYPE,
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_FECHA_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.FECHA_MANTENIMIENTO%TYPE,
    P_ID_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_MAQUINARIA_MANTENIMIENTO_ELIMINAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.PLACA%TYPE,
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_FECHA_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.FECHA_MANTENIMIENTO%TYPE
);

-----PROCEDIMIENTOS DE LA TABLA DE TAJO_MAQUINARIA_TB
PROCEDURE TAJO_MAQUINARIA_INSERTAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.PLACA%TYPE,
    P_MODELO IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.MODELO%TYPE,
    P_HORAS_TRABAJADAS IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.HORAS_TRABAJADAS%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_MAQUINARIA_MODIFICAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.PLACA%TYPE,
    P_MODELO_NUEVO IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.MODELO%TYPE,
    P_HORAS_NUEVAS IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.HORAS_TRABAJADAS%TYPE
);

PROCEDURE TAJO_MAQUINARIA_ELIMINAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.PLACA%TYPE
);

-----PROCEDIMIENTOS DE LA TABLA DE MATERIALES
PROCEDURE TAJO_MATERIALES_INSERTAR_SP (
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_MATERIAL%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_MATERIALES_TB.NOMBRE%TYPE,
    P_UNIDAD_MEDIDA IN TAJO_PROYECTO.TAJO_MATERIALES_TB.UNIDAD_MEDIDA%TYPE,
    P_FUNCION IN TAJO_PROYECTO.TAJO_MATERIALES_TB.FUNCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_MATERIALES_MODIFICAR_SP (
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_MATERIAL%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_MATERIALES_TB.NOMBRE%TYPE,
    P_UNIDAD_NUEVA IN TAJO_PROYECTO.TAJO_MATERIALES_TB.UNIDAD_MEDIDA%TYPE,
    P_FUNCION_NUEVA IN TAJO_PROYECTO.TAJO_MATERIALES_TB.FUNCION%TYPE,
    P_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_ESTADO%TYPE -- <--- AGREGAR ESTO
);

PROCEDURE TAJO_MATERIALES_ELIMINAR_SP (
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_MATERIAL%TYPE
);

-----PROCEDIMIENTOS DE LA TABLA DE METODO DE PAGO
PROCEDURE TAJO_METODO_PAGO_INSERTAR_SP (
    P_ID_METODO_PAGO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_METODO_PAGO_MODIFICAR_SP (
    P_ID_METODO_PAGO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.NOMBRE%TYPE
);

PROCEDURE TAJO_METODO_PAGO_ELIMINAR_SP (
    P_ID_METODO_PAGO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.ID_METODO_PAGO%TYPE
);

---PROCEDIMIENTOS DE LA TABLA DE PAGO USUARIOS
PROCEDURE TAJO_PAGOS_USUARIOS_INSERTAR_SP (
    P_ID_PAGO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_PAGO%TYPE,
    P_ID_PLANILLA IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_PLANILLA%TYPE,
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.IDENTIFICACION%TYPE,
    P_SALARIO_BASE IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.SALARIO_BASE%TYPE,
    P_ID_DEDUCCION IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_DEDUCCION%TYPE,
    P_ID_BONIFICACION IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_BONIFICACION%TYPE,
    P_SALARIO_NETO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.SALARIO_NETO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_PAGOS_USUARIOS_MODIFICAR_SP (
    P_ID_PAGO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_PAGO%TYPE,
    P_SALARIO_BASE_NUEVO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.SALARIO_BASE%TYPE,
    P_SALARIO_NETO_NUEVO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.SALARIO_NETO%TYPE
);

PROCEDURE TAJO_PAGOS_USUARIOS_ELIMINAR_SP (
    P_ID_PAGO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_PAGO%TYPE
);

----PROCEDIMIENTOS DE LA TABLA DE TAJO_PLANILLAS_TB
PROCEDURE TAJO_PLANILLAS_INSERTAR_SP (
    P_ID_PLANILLA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.ID_PLANILLA%TYPE,
    P_DESCRIPCION IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.DESCRIPCION%TYPE,
    P_FECHA_INICIO IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_INICIO%TYPE,
    P_FECHA_FINAL IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_FINAL%TYPE,
    P_FECHA_PAGO IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_PAGO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_PLANILLAS_MODIFICAR_SP (
    P_ID_PLANILLA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.ID_PLANILLA%TYPE,
    P_DESCRIPCION_NUEVA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.DESCRIPCION%TYPE,
    P_FECHA_INICIO_NUEVA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_INICIO%TYPE,
    P_FECHA_FINAL_NUEVA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_FINAL%TYPE,
    P_FECHA_PAGO_NUEVA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_PAGO%TYPE
);

PROCEDURE TAJO_PLANILLAS_ELIMINAR_SP (
    P_ID_PLANILLA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.ID_PLANILLA%TYPE
);

-----PROCEDIMIENTOS DE LA TABLA DE PRODUCCION
PROCEDURE TAJO_PRODUCCION_INSERTAR_SP (
    P_ID_PRODUCCION IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_PRODUCCION%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.CANTIDAD%TYPE,
    P_FECHA_PRODUCCION IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.FECHA_PRODUCCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_PRODUCCION_MODIFICAR_SP (
    P_ID_PRODUCCION IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_PRODUCCION%TYPE,
    P_ID_MATERIAL_NUEVO IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD_NUEVA IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.CANTIDAD%TYPE,
    P_FECHA_NUEVA IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.FECHA_PRODUCCION%TYPE,
    P_ID_ESTADO_NUEVO IN NUMBER
);

PROCEDURE TAJO_PRODUCCION_ELIMINAR_SP (
    P_ID_PRODUCCION IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_PRODUCCION%TYPE
);

----PROCEDIMIENTOS DE LA TABLA DE ROLES
PROCEDURE TAJO_ROLES_INSERTAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_ROLES_TB.IDENTIFICACION%TYPE,
    P_ID_ROL IN TAJO_PROYECTO.TAJO_ROLES_TB.ID_ROL%TYPE,
    P_NOMBRE_ROL IN TAJO_PROYECTO.TAJO_ROLES_TB.NOMBRE_ROL%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_ROLES_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_ROLES_MODIFICAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_ROLES_TB.IDENTIFICACION%TYPE,
    P_NOMBRE_ROL_NUEVO IN TAJO_PROYECTO.TAJO_ROLES_TB.NOMBRE_ROL%TYPE
);

PROCEDURE TAJO_ROLES_ELIMINAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_ROLES_TB.IDENTIFICACION%TYPE,
    P_ID_ROL IN TAJO_PROYECTO.TAJO_ROLES_TB.ID_ROL%TYPE
);

----PROCEDIMIENTOS DE LA TABLA DE TELFONOS
PROCEDURE TAJO_TELEFONOS_INSERTAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.IDENTIFICACION%TYPE,
    P_TELEFONO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.TELEFONO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_TELEFONOS_MODIFICAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.IDENTIFICACION%TYPE,
    P_TELEFONO_VIEJO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.TELEFONO%TYPE,
    P_TELEFONO_NUEVO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.TELEFONO%TYPE
);

PROCEDURE TAJO_TELEFONOS_ELIMINAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.IDENTIFICACION%TYPE,
    P_TELEFONO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.TELEFONO%TYPE
);

-----PROCEDIMIENTOS PARA LA TABLA DE TIPO DE CLIENTES
PROCEDURE TAJO_TIPO_CLIENTE_INSERTAR_SP (
    P_ID_TIPO_CLIENTE IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.ID_TIPO_CLIENTE%TYPE,
    P_NOMBRE_TIPO IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.NOMBRE_TIPO_CLIENTE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_TIPO_CLIENTE_MODIFICAR_SP (
    P_ID_TIPO_CLIENTE IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.ID_TIPO_CLIENTE%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.NOMBRE_TIPO_CLIENTE%TYPE
);

PROCEDURE TAJO_TIPO_CLIENTE_ELIMINAR_SP (
    P_ID_TIPO_CLIENTE IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.ID_TIPO_CLIENTE%TYPE
);

----PROCEDIMIENTOS PARA LA TABLA DE TIPO_MAQUINARIA
PROCEDURE TAJO_TIPO_MAQUINARIA_INSERTAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.PLACA%TYPE,
    P_ID_TIPO IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.ID_TIPO_MAQUINARIA%TYPE,
    P_DESCRIPCION IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_TIPO_MAQUINARIA_MODIFICAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.PLACA%TYPE,
    P_DESCRIPCION_NUEVA IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.DESCRIPCION%TYPE
);

PROCEDURE TAJO_TIPO_MAQUINARIA_ELIMINAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.PLACA%TYPE
);

----PROCEDIMIENTOS DE TABLA DE TIPOS DE MOVIMIENTO DE INVENTARIO
PROCEDURE TAJO_TIPO_MOVIMIENTO_INVENTARIO_INSERTAR_SP (
    P_ID_TIPO_MOVIMIENTO IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO_INVENTARIO%TYPE,
    P_DESCRIPCION IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_TIPO_MOVIMIENTO_INVENTARIO_MODIFICAR_SP (
    P_ID_TIPO_MOVIMIENTO IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO_INVENTARIO%TYPE,
    P_DESCRIPCION_NUEVA IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.DESCRIPCION%TYPE
);

PROCEDURE TAJO_TIPO_MOVIMIENTO_INVENTARIO_ELIMINAR_SP (
    P_ID_TIPO_MOVIMIENTO IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO_INVENTARIO%TYPE
);
----PROCEDIMIENTOS DE LA TABLA DE TURNOS
PROCEDURE TAJO_TURNOS_INSERTAR_SP (
    P_ID_TURNO IN TAJO_PROYECTO.TAJO_TURNOS_TB.ID_TURNO%TYPE,
    P_NOMBRE_TURNO IN TAJO_PROYECTO.TAJO_TURNOS_TB.NOMBRE_TURNO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TURNOS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_TURNOS_MODIFICAR_SP (
    P_ID_TURNO IN TAJO_PROYECTO.TAJO_TURNOS_TB.ID_TURNO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_TURNOS_TB.NOMBRE_TURNO%TYPE
);

PROCEDURE TAJO_TURNOS_ELIMINAR_SP (
    P_ID_TURNO IN TAJO_PROYECTO.TAJO_TURNOS_TB.ID_TURNO%TYPE
);

----PROCEDIMIENTOS DE LA TABLA DE USUSARIOS
PROCEDURE TAJO_USUARIOS_INSERTAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_USUARIOS_TB.IDENTIFICACION%TYPE,
    P_NOMBRE         IN TAJO_PROYECTO.TAJO_USUARIOS_TB.NOMBRE_USUARIO%TYPE,
    P_APELLIDO_PATERNO IN TAJO_PROYECTO.TAJO_USUARIOS_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN TAJO_PROYECTO.TAJO_USUARIOS_TB.APELLIDO_MATERNO%TYPE,
    P_EDAD           IN TAJO_PROYECTO.TAJO_USUARIOS_TB.EDAD%TYPE,
    P_FECHA_INGRESO  IN TAJO_PROYECTO.TAJO_USUARIOS_TB.FECHA_INGRESO%TYPE,
    P_ID_TURNO       IN TAJO_PROYECTO.TAJO_USUARIOS_TB.ID_TURNO%TYPE,
    P_PLACA          IN TAJO_PROYECTO.TAJO_USUARIOS_TB.PLACA%TYPE,
    P_ID_ESTADO      IN TAJO_PROYECTO.TAJO_USUARIOS_TB.ID_ESTADO%TYPE,
    P_CONTRASENA     IN TAJO_PROYECTO.TAJO_USUARIOS_TB.CONTRASENA%TYPE
);

PROCEDURE TAJO_USUARIOS_MODIFICAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_USUARIOS_TB.IDENTIFICACION%TYPE,
    P_NOMBRE         IN TAJO_PROYECTO.TAJO_USUARIOS_TB.NOMBRE_USUARIO%TYPE,
    P_APE_PATERNO    IN TAJO_PROYECTO.TAJO_USUARIOS_TB.APELLIDO_PATERNO%TYPE,
    P_APE_MATERNO    IN TAJO_PROYECTO.TAJO_USUARIOS_TB.APELLIDO_MATERNO%TYPE,
    P_EDAD           IN TAJO_PROYECTO.TAJO_USUARIOS_TB.EDAD%TYPE,
    P_ID_TURNO_NUEVO IN TAJO_PROYECTO.TAJO_USUARIOS_TB.ID_TURNO%TYPE,
    P_PLACA_NUEVA    IN TAJO_PROYECTO.TAJO_USUARIOS_TB.PLACA%TYPE,
    P_ID_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_USUARIOS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_USUARIOS_ELIMINAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_USUARIOS_TB.IDENTIFICACION%TYPE
);


----PROCEDIMIENTOS DE LA TABLA DE VENTAS
PROCEDURE TAJO_VENTAS_INSERTAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_VENTA%TYPE,
    P_CEDULA IN TAJO_PROYECTO.TAJO_VENTAS_TB.CEDULA%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_MATERIAL%TYPE, -- NUEVO FK
    P_CANTIDAD IN TAJO_PROYECTO.TAJO_VENTAS_TB.CANTIDAD_VENTA%TYPE,
    P_PRECIO IN TAJO_PROYECTO.TAJO_VENTAS_TB.PRECIO%TYPE,
    P_FECHA IN TAJO_PROYECTO.TAJO_VENTAS_TB.FECHA_VENTA%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_ESTADO%TYPE
);

PROCEDURE TAJO_VENTAS_MODIFICAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_VENTA%TYPE,
    P_ID_MATERIAL_NUEVO IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD_NUEVA IN TAJO_PROYECTO.TAJO_VENTAS_TB.CANTIDAD_VENTA%TYPE,
    P_PRECIO_NUEVO IN TAJO_PROYECTO.TAJO_VENTAS_TB.PRECIO%TYPE
);

PROCEDURE TAJO_VENTAS_ELIMINAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_VENTA%TYPE
);



END TAJO_PROYECTO_FINAL_PKG;