create or replace PACKAGE BODY TAJO_PROYECTO_FINAL_PKG  AS

----FUNCIONES-------

FUNCTION TAJO_USUARIOS_VALIDAR_ACCESO_FN (
    P_IDENTIFICACION IN TAJO_USUARIOS_TB.IDENTIFICACION%TYPE,
    P_CONTRASENA IN TAJO_USUARIOS_TB.CONTRASENA%TYPE
) RETURN NUMBER IS
    V_ROL NUMBER := 0;
BEGIN
    -- Buscamos el ID_ROL haciendo el cruce por IDENTIFICACION
    SELECT R.ID_ROL 
    INTO V_ROL
    FROM TAJO_USUARIOS_TB U
    INNER JOIN TAJO_ROLES_TB R ON U.IDENTIFICACION = R.IDENTIFICACION
    WHERE U.IDENTIFICACION = P_IDENTIFICACION 
      AND U.CONTRASENA = P_CONTRASENA 
      AND U.ID_ESTADO = 1;

    RETURN V_ROL;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0; -- No existe el usuario o contraseña mala
    WHEN OTHERS THEN
        RETURN 0;
END TAJO_USUARIOS_VALIDAR_ACCESO_FN;

-----
FUNCTION TAJO_USUARIOS_OBTENER_NOMBRE_COMPLETO_FN (
    P_IDENTIFICACION IN TAJO_USUARIOS_TB.IDENTIFICACION%TYPE
) RETURN VARCHAR2 IS
    V_NOMBRE_COMPLETO VARCHAR2(500) := 'USUARIO NO ENCONTRADO';
    CURSOR C_USUARIOS IS
        SELECT NOMBRE_USUARIO, APELLIDO_PATERNO, APELLIDO_MATERNO
        FROM TAJO_USUARIOS_TB
        WHERE IDENTIFICACION = P_IDENTIFICACION;
BEGIN
    FOR REC IN C_USUARIOS LOOP
        V_NOMBRE_COMPLETO := REC.NOMBRE_USUARIO || ' ' || REC.APELLIDO_PATERNO || ' ' || REC.APELLIDO_MATERNO;
    END LOOP;
    RETURN V_NOMBRE_COMPLETO;
END TAJO_USUARIOS_OBTENER_NOMBRE_COMPLETO_FN;

-----
FUNCTION TAJO_TURNOS_USUARIOS_CONTAR_FN (
    P_ID_TURNO IN TAJO_TURNOS_TB.ID_TURNO%TYPE
) RETURN NUMBER IS
    V_CONTADOR NUMBER := 0;
    CURSOR C_CONTEO IS
        SELECT ID_TURNO 
        FROM TAJO_USUARIOS_TB
        WHERE ID_TURNO = P_ID_TURNO;
BEGIN
    FOR REC IN C_CONTEO LOOP
        V_CONTADOR := V_CONTADOR + 1;
    END LOOP;
    RETURN V_CONTADOR;
END TAJO_TURNOS_USUARIOS_CONTAR_FN;

------
FUNCTION TAJO_VENTAS_TOTAL_CLIENTE_FN (
    P_CEDULA IN TAJO_CLIENTES_TB.CEDULA%TYPE
) RETURN NUMBER IS
    V_TOTAL NUMBER := 0;
    CURSOR C_VENTAS IS
        SELECT PRECIO 
        FROM TAJO_VENTAS_TB
        WHERE CEDULA = P_CEDULA AND ID_ESTADO = 1;
BEGIN
    FOR REC IN C_VENTAS LOOP
        V_TOTAL := V_TOTAL + REC.PRECIO;
    END LOOP;
    RETURN V_TOTAL;
END TAJO_VENTAS_TOTAL_CLIENTE_FN;
-----
FUNCTION TAJO_VENTAS_ACTIVAS_CLIENTE_FN(
        P_CEDULA IN TAJO_CLIENTES_TB.CEDULA%TYPE
    ) RETURN NUMBER IS
        V_CANTIDAD NUMBER := 0;
    BEGIN
        -- Cuenta cuántas ventas tiene ese cliente en estado 1 (Pendiente/Proceso)
        SELECT COUNT(*)
        INTO V_CANTIDAD
        FROM TAJO_VENTAS_TB
        WHERE CEDULA = P_CEDULA
          AND ID_ESTADO = 1;
          
        RETURN V_CANTIDAD;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0;
    END TAJO_VENTAS_ACTIVAS_CLIENTE_FN;

------
FUNCTION TAJO_INVENTARIO_STOCK_ACTUAL_MATERIAL_FN (
    P_ID_MATERIAL IN TAJO_INVENTARIO_TB.ID_MATERIAL%TYPE
) RETURN NUMBER IS
    V_STOCK_TOTAL NUMBER := 0;
    CURSOR C_STOCK IS
        SELECT CANTIDAD_MATERIAL 
        FROM TAJO_INVENTARIO_TB
        WHERE ID_MATERIAL = P_ID_MATERIAL AND ID_ESTADO = 1;
BEGIN
    FOR REC IN C_STOCK LOOP
        V_STOCK_TOTAL := V_STOCK_TOTAL + REC.CANTIDAD_MATERIAL;
    END LOOP;
    RETURN V_STOCK_TOTAL;
END TAJO_INVENTARIO_STOCK_ACTUAL_MATERIAL_FN;

------
FUNCTION TAJO_MAQUINARIA_ACTIVA_CONTAR_FN 
RETURN NUMBER 
IS
    V_MAQUINAS NUMBER := 0;
    CURSOR C_MAQUINAS IS
        SELECT PLACA 
        FROM TAJO_MAQUINARIA_TB
        WHERE ID_ESTADO = 1;
BEGIN
    FOR REC IN C_MAQUINAS LOOP
        V_MAQUINAS := V_MAQUINAS + 1;
    END LOOP;
    RETURN V_MAQUINAS;
END TAJO_MAQUINARIA_ACTIVA_CONTAR_FN;

-------
FUNCTION TAJO_FACTURACION_MONTO_TOTAL_FN (
    P_CEDULA IN TAJO_FACTURACION_TB.CEDULA%TYPE
) RETURN NUMBER IS
    V_SUMA_TOTAL NUMBER := 0;
    CURSOR C_FACTURAS IS
        SELECT MONTO_TOTAL 
        FROM TAJO_FACTURACION_TB
        WHERE CEDULA = P_CEDULA AND ID_ESTADO IN (11,12);
BEGIN
    FOR REC IN C_FACTURAS LOOP
        V_SUMA_TOTAL := V_SUMA_TOTAL + REC.MONTO_TOTAL;
    END LOOP;
    RETURN V_SUMA_TOTAL;
END TAJO_FACTURACION_MONTO_TOTAL_FN;

-----
FUNCTION TAJO_MAQUINARIA_HORAS_TOTALES_FN 
RETURN NUMBER 
IS
    V_TOTAL_HORAS NUMBER := 0;
    CURSOR C_HORAS IS
        SELECT HORAS_TRABAJADAS 
        FROM TAJO_MAQUINARIA_TB
        WHERE ID_ESTADO = 1;
BEGIN
    FOR REC IN C_HORAS LOOP
        V_TOTAL_HORAS := V_TOTAL_HORAS + REC.HORAS_TRABAJADAS;
    END LOOP;
    RETURN V_TOTAL_HORAS;
END TAJO_MAQUINARIA_HORAS_TOTALES_FN;

----
FUNCTION TAJO_TRANSPORTE_CANTIDAD_MATERIAL_FN (
    P_ID_MATERIAL IN TAJO_CONTROL_TRANSPORTE_TB.ID_MATERIAL%TYPE
) RETURN NUMBER IS
    V_CANTIDAD_TRANS NUMBER := 0;
    CURSOR C_TRANSPORTE IS
        SELECT CANTIDAD_TRANSPORTADA 
        FROM TAJO_CONTROL_TRANSPORTE_TB
        WHERE ID_MATERIAL = P_ID_MATERIAL AND ID_ESTADO IN (7,8);
BEGIN
    FOR REC IN C_TRANSPORTE LOOP
        V_CANTIDAD_TRANS := V_CANTIDAD_TRANS + REC.CANTIDAD_TRANSPORTADA;
    END LOOP;
    RETURN V_CANTIDAD_TRANS;
END TAJO_TRANSPORTE_CANTIDAD_MATERIAL_FN;

----
FUNCTION TAJO_DEDUCCIONES_PORCENTAJE_TOTAL_FN 
RETURN NUMBER 
IS
    V_PORCENTAJE_SUMA NUMBER := 0;
    CURSOR C_DEDUCCIONES IS
        SELECT PORCENTAJE 
        FROM TAJO_DEDUCCIONES_TB
        WHERE ID_ESTADO = 1;
BEGIN
    FOR REC IN C_DEDUCCIONES LOOP
        V_PORCENTAJE_SUMA := V_PORCENTAJE_SUMA + REC.PORCENTAJE;
    END LOOP;
    RETURN V_PORCENTAJE_SUMA;
END TAJO_DEDUCCIONES_PORCENTAJE_TOTAL_FN;

----
FUNCTION TAJO_PRODUCCION_FECHA_ESPECIFICA_FN (
    P_FECHA IN DATE
) RETURN NUMBER IS
    V_TOTAL_PROD NUMBER := 0;
    CURSOR C_PRODUCCION IS
        SELECT CANTIDAD 
        FROM TAJO_PRODUCCION_TB
        WHERE TRUNC(FECHA_PRODUCCION) = TRUNC(P_FECHA) AND ID_ESTADO = 8;
BEGIN
    FOR REC IN C_PRODUCCION LOOP
        V_TOTAL_PROD := V_TOTAL_PROD + REC.CANTIDAD;
    END LOOP;
    RETURN V_TOTAL_PROD;
END TAJO_PRODUCCION_FECHA_ESPECIFICA_FN;

----
FUNCTION TAJO_PLANILLAS_TOTAL_PAGADO_FN RETURN NUMBER IS
    V_TOTAL_PLANILLA NUMBER := 0;
    CURSOR C_PAGOS IS
        SELECT SALARIO_NETO 
        FROM TAJO_PAGOS_USUARIOS_TB
        WHERE ID_ESTADO = 10; --EL 10 AQUI ES EL ESTADO DE PAGADO
BEGIN
    FOR REC IN C_PAGOS LOOP
        V_TOTAL_PLANILLA := V_TOTAL_PLANILLA + REC.SALARIO_NETO;
    END LOOP;
    RETURN V_TOTAL_PLANILLA;
END TAJO_PLANILLAS_TOTAL_PAGADO_FN;

----
FUNCTION TAJO_FACTURACION_CALCULO_IVA_FN (
    P_ID_FACTURA IN TAJO_FACTURACION_TB.ID_FACTURA%TYPE
) RETURN NUMBER IS
    V_IVA NUMBER := 0;
    CURSOR C_IVA IS
        SELECT MONTO_TOTAL 
        FROM TAJO_FACTURACION_TB
        WHERE ID_FACTURA = P_ID_FACTURA 
          AND ID_ESTADO IN (10, 11);
BEGIN
    FOR REC IN C_IVA LOOP
        V_IVA := REC.MONTO_TOTAL * 0.13;
    END LOOP;
    
    RETURN V_IVA;
END TAJO_FACTURACION_CALCULO_IVA_FN;

----
FUNCTION TAJO_MAQUINARIA_CONTAR_MANTENIMIENTOS_FN (
    P_PLACA IN TAJO_MAQUINARIA_MANTENIMIENTO_TB.PLACA%TYPE
) RETURN NUMBER IS
    V_CONTEO NUMBER := 0;
    CURSOR C_MANTENIMIENTOS IS
        SELECT PLACA 
        FROM TAJO_MAQUINARIA_MANTENIMIENTO_TB
        WHERE PLACA = P_PLACA;
BEGIN
    FOR REC IN C_MANTENIMIENTOS LOOP
        V_CONTEO := V_CONTEO + 1;
    END LOOP;
    RETURN V_CONTEO;
END TAJO_MAQUINARIA_CONTAR_MANTENIMIENTOS_FN;

----
FUNCTION TAJO_CLIENTES_CONTAR_POR_TIPO_FN (
    P_ID_TIPO IN TAJO_CLIENTES_TB.ID_TIPO_CLIENTE%TYPE
) RETURN NUMBER IS
    V_CANTIDAD NUMBER := 0;
    CURSOR C_CLIENTES IS
        SELECT CEDULA 
        FROM TAJO_CLIENTES_TB
        WHERE ID_TIPO_CLIENTE = P_ID_TIPO AND ID_ESTADO = 1;
BEGIN
    FOR REC IN C_CLIENTES LOOP
        V_CANTIDAD := V_CANTIDAD + 1;
    END LOOP;
    RETURN V_CANTIDAD;
END TAJO_CLIENTES_CONTAR_POR_TIPO_FN;

----
FUNCTION TAJO_USUARIOS_FECHA_INGRESO_FN (
    P_ID IN TAJO_USUARIOS_TB.IDENTIFICACION%TYPE
) RETURN DATE IS
    V_FECHA DATE;
    
    CURSOR C_FECHA IS
        SELECT FECHA_INGRESO 
        FROM TAJO_USUARIOS_TB
        WHERE IDENTIFICACION = P_ID;
BEGIN
    V_FECHA := NULL;
    
    FOR REC IN C_FECHA LOOP
        V_FECHA := REC.FECHA_INGRESO;
    END LOOP;
    
    RETURN V_FECHA;
END TAJO_USUARIOS_FECHA_INGRESO_FN;


---PROCEDIMIENTOS ALMACENADOS-----

----PROCEDIMIENTOS DE BONIFICACIONES

PROCEDURE TAJO_BONIFICACIONES_INSERTAR_SP (
    P_ID_BONIFICACION IN TAJO_BONIFICACIONES_TB.ID_BONIFICACION%TYPE,
    P_NOMBRE IN TAJO_BONIFICACIONES_TB.NOMBRE%TYPE,
    P_PORCENTAJE IN TAJO_BONIFICACIONES_TB.PORCENTAJE%TYPE,
    P_ID_ESTADO IN TAJO_BONIFICACIONES_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_BONIFICACIONES_TB (ID_BONIFICACION, NOMBRE, PORCENTAJE, ID_ESTADO)
    VALUES (P_ID_BONIFICACION, P_NOMBRE, P_PORCENTAJE, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE BONIFICACIÓN INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID ' || P_ID_BONIFICACION || ' YA SE ENCUENTRA REGISTRADO.');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO O SUPERA EL TAMAÑO PERMITIDO.');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_BONIFICACIONES_INSERTAR_SP;
-----
PROCEDURE TAJO_BONIFICACIONES_MODIFICAR_SP (
    P_ID_BONIFICACION IN TAJO_BONIFICACIONES_TB.ID_BONIFICACION%TYPE,
    P_NOMBRE_NUEVO IN TAJO_BONIFICACIONES_TB.NOMBRE%TYPE,
    P_PORCENTAJE_NUEVO IN TAJO_BONIFICACIONES_TB.PORCENTAJE%TYPE
) IS
BEGIN
    UPDATE TAJO_BONIFICACIONES_TB
    SET NOMBRE = P_NOMBRE_NUEVO,
        PORCENTAJE = P_PORCENTAJE_NUEVO
    WHERE ID_BONIFICACION = P_ID_BONIFICACION;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('BONIFICACIÓN MODIFICADA EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID ' || P_ID_BONIFICACION || ' NO EXISTE EN LA TABLA.');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO TIENEN EL FORMATO CORRECTO.');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_BONIFICACIONES_MODIFICAR_SP;
------
PROCEDURE TAJO_BONIFICACIONES_ELIMINAR_SP (
    P_ID_BONIFICACION IN TAJO_BONIFICACIONES_TB.ID_BONIFICACION%TYPE
) IS
    V_ID_BONIFICACION TAJO_BONIFICACIONES_TB.ID_BONIFICACION%TYPE;
BEGIN
    SELECT ID_BONIFICACION INTO V_ID_BONIFICACION
    FROM TAJO_BONIFICACIONES_TB
    WHERE ID_BONIFICACION = P_ID_BONIFICACION;

    UPDATE TAJO_BONIFICACIONES_TB
    SET ID_ESTADO = 2  -- Inactivo
    WHERE ID_BONIFICACION = P_ID_BONIFICACION;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO CON EL ID: ' || P_ID_BONIFICACION || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ NINGÚN REGISTRO CON EL ID ' || P_ID_BONIFICACION);
    
    WHEN VALUE_ERROR THEN ROLLBACK; 
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID PROPORCIONADO TIENE UN FORMATO NO VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_BONIFICACIONES_ELIMINAR_SP;

-----PROCEDIMIENTOS DE CLIENTES

PROCEDURE TAJO_CLIENTES_INSERTAR_SP (
    P_CEDULA IN TAJO_CLIENTES_TB.CEDULA%TYPE,
    P_NOMBRE_CLIENTE IN TAJO_CLIENTES_TB.NOMBRE_CLIENTE%TYPE,
    P_APELLIDO_PATERNO IN TAJO_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN TAJO_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
    P_ID_TIPO_CLIENTE IN TAJO_CLIENTES_TB.ID_TIPO_CLIENTE%TYPE,
    P_CONTRASENA IN TAJO_CLIENTES_TB.CONTRASENA%TYPE,
    P_ID_ESTADO IN TAJO_CLIENTES_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_CLIENTES_TB (CEDULA, NOMBRE_CLIENTE, APELLIDO_PATERNO, APELLIDO_MATERNO, ID_TIPO_CLIENTE, CONTRASENA, ID_ESTADO)
    VALUES (P_CEDULA, P_NOMBRE_CLIENTE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_ID_TIPO_CLIENTE, P_CONTRASENA, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE CLIENTE INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA CÉDULA ' || P_CEDULA || ' YA SE ENCUENTRA REGISTRADA.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO O SUPERA EL TAMAÑO PERMITIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_CLIENTES_INSERTAR_SP;
-----
PROCEDURE TAJO_CLIENTES_MODIFICAR_SP (
    P_CEDULA IN TAJO_CLIENTES_TB.CEDULA%TYPE,
    P_NOMBRE_CLIENTE_NUEVO IN TAJO_CLIENTES_TB.NOMBRE_CLIENTE%TYPE,
    P_APELLIDO_PATERNO_NUEVO IN TAJO_CLIENTES_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO_NUEVO IN TAJO_CLIENTES_TB.APELLIDO_MATERNO%TYPE,
    P_ID_TIPO_CLIENTE_NUEVO IN TAJO_CLIENTES_TB.ID_TIPO_CLIENTE%TYPE
) IS
BEGIN
    UPDATE TAJO_CLIENTES_TB
    SET NOMBRE_CLIENTE = P_NOMBRE_CLIENTE_NUEVO,
        APELLIDO_PATERNO = P_APELLIDO_PATERNO_NUEVO,
        APELLIDO_MATERNO = P_APELLIDO_MATERNO_NUEVO,
        ID_TIPO_CLIENTE = P_ID_TIPO_CLIENTE_NUEVO
    WHERE CEDULA = P_CEDULA;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID ' || P_CEDULA || ' NO EXISTE EN LA TABLA.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO TIENEN EL FORMATO CORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_CLIENTES_MODIFICAR_SP;
----
PROCEDURE TAJO_CLIENTES_ELIMINAR_SP (
    P_CEDULA IN TAJO_CLIENTES_TB.CEDULA%TYPE
) IS
    V_CEDULA TAJO_CLIENTES_TB.CEDULA%TYPE;
BEGIN
    SELECT CEDULA INTO V_CEDULA
    FROM TAJO_CLIENTES_TB
    WHERE CEDULA = P_CEDULA;

    UPDATE TAJO_CLIENTES_TB
    SET ID_ESTADO = 2
    WHERE CEDULA = P_CEDULA;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO CON EL ID: ' || P_CEDULA || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ NINGÚN REGISTRO CON EL ID ' || P_CEDULA);
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID PROPORCIONADO TIENE UN FORMATO NO VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_CLIENTES_ELIMINAR_SP;

----PROCEDIMIENTOS  DE CONTROL TRANSPORTE
PROCEDURE TAJO_TRANSPORTE_INSERTAR_SP (
    P_ID_TRANSPORTE IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_TRANSPORTE%TYPE,
    P_PLACA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.PLACA%TYPE,
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.IDENTIFICACION%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD_TRANSPORTADA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.CANTIDAD_TRANSPORTADA%TYPE,
    P_PRECIO_TRANSPORTE IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.PRECIO_TRANSPORTE%TYPE,
    P_DESTINO IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.DESTINO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB (
        ID_TRANSPORTE, PLACA, IDENTIFICACION, ID_MATERIAL, 
        CANTIDAD_TRANSPORTADA, PRECIO_TRANSPORTE, DESTINO, ID_ESTADO
    )
    VALUES (
        P_ID_TRANSPORTE, P_PLACA, P_IDENTIFICACION, P_ID_MATERIAL, 
        P_CANTIDAD_TRANSPORTADA, P_PRECIO_TRANSPORTE, P_DESTINO, P_ID_ESTADO
    );
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID ' || P_ID_TRANSPORTE || ' YA SE ENCUENTRA REGISTRADO.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO O SUPERA EL TAMAÑO PERMITIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_TRANSPORTE_INSERTAR_SP;
-----
PROCEDURE TAJO_TRANSPORTE_MODIFICAR_SP (
    P_ID_TRANSPORTE IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_TRANSPORTE%TYPE,
    P_PLACA_NUEVA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.PLACA%TYPE,
    P_IDENTIFICACION_NUEVA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.IDENTIFICACION%TYPE,
    P_CANTIDAD_NUEVA IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.CANTIDAD_TRANSPORTADA%TYPE,
    P_PRECIO_NUEVO IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.PRECIO_TRANSPORTE%TYPE,
    P_DESTINO_NUEVO IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.DESTINO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB
    SET PLACA = P_PLACA_NUEVA,
        IDENTIFICACION = P_IDENTIFICACION_NUEVA,
        CANTIDAD_TRANSPORTADA = P_CANTIDAD_NUEVA,
        PRECIO_TRANSPORTE = P_PRECIO_NUEVO,
        DESTINO = P_DESTINO_NUEVO
    WHERE ID_TRANSPORTE = P_ID_TRANSPORTE;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID ' || P_ID_TRANSPORTE || ' NO EXISTE EN LA TABLA.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO TIENEN EL FORMATO CORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_TRANSPORTE_MODIFICAR_SP;
-----
PROCEDURE TAJO_TRANSPORTE_ELIMINAR_SP (
    P_ID_TRANSPORTE IN TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_TRANSPORTE%TYPE
) IS
    V_ID_TRANSPORTE TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB.ID_TRANSPORTE%TYPE;
BEGIN
    SELECT ID_TRANSPORTE INTO V_ID_TRANSPORTE
    FROM TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB
    WHERE ID_TRANSPORTE = P_ID_TRANSPORTE;

    UPDATE TAJO_PROYECTO.TAJO_CONTROL_TRANSPORTE_TB
    SET ID_ESTADO = 2
    WHERE ID_TRANSPORTE = P_ID_TRANSPORTE;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO CON EL ID: ' || P_ID_TRANSPORTE || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ NINGÚN REGISTRO CON EL ID ' || P_ID_TRANSPORTE);
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID PROPORCIONADO TIENE UN FORMATO NO VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_TRANSPORTE_ELIMINAR_SP;

----PROCEDIMIENTOS DE CORREOS
PROCEDURE TAJO_CORREOS_INSERTAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_CORREOS_TB.IDENTIFICACION%TYPE,
    P_CORREO IN TAJO_PROYECTO.TAJO_CORREOS_TB.CORREO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_CORREOS_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_CORREOS_TB (IDENTIFICACION, CORREO, ID_ESTADO)
    VALUES (P_IDENTIFICACION, P_CORREO, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE CORREO INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL CORREO O LA IDENTIFICACIÓN YA SE ENCUENTRAN REGISTRADOS.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO O SUPERA EL TAMAÑO PERMITIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_CORREOS_INSERTAR_SP;
----
PROCEDURE TAJO_CORREOS_MODIFICAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_CORREOS_TB.IDENTIFICACION%TYPE,
    P_CORREO_NUEVO IN TAJO_PROYECTO.TAJO_CORREOS_TB.CORREO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_CORREOS_TB
    SET CORREO = P_CORREO_NUEVO
    WHERE IDENTIFICACION = P_IDENTIFICACION;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE CORREO MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA IDENTIFICACIÓN ' || P_IDENTIFICACION || ' NO EXISTE EN LA TABLA DE CORREOS.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO TIENEN EL FORMATO CORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_CORREOS_MODIFICAR_SP;
----
PROCEDURE TAJO_CORREOS_ELIMINAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_CORREOS_TB.IDENTIFICACION%TYPE
) IS
    V_IDENTIFICACION TAJO_PROYECTO.TAJO_CORREOS_TB.IDENTIFICACION%TYPE;
BEGIN
    SELECT IDENTIFICACION INTO V_IDENTIFICACION
    FROM TAJO_PROYECTO.TAJO_CORREOS_TB
    WHERE IDENTIFICACION = P_IDENTIFICACION;

    UPDATE TAJO_PROYECTO.TAJO_CORREOS_TB
    SET ID_ESTADO = 2 -- Inactivo
    WHERE IDENTIFICACION = P_IDENTIFICACION;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO CON IDENTIFICACIÓN: ' || P_IDENTIFICACION || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ NINGÚN CORREO PARA LA IDENTIFICACIÓN ' || P_IDENTIFICACION);
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL FORMATO DE LA IDENTIFICACIÓN NO ES VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_CORREOS_ELIMINAR_SP;

---PROCEDIMINETOS DE DUCCIONES
PROCEDURE TAJO_DEDUCCIONES_INSERTAR_SP (
    P_ID_DEDUCCION IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.ID_DEDUCCION%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.NOMBRE%TYPE,
    P_PORCENTAJE IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.PORCENTAJE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_DEDUCCIONES_TB (ID_DEDUCCION, NOMBRE, PORCENTAJE, ID_ESTADO)
    VALUES (P_ID_DEDUCCION, P_NOMBRE, P_PORCENTAJE, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID ' || P_ID_DEDUCCION || ' YA SE ENCUENTRA REGISTRADO.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO O SUPERA EL TAMAÑO PERMITIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_DEDUCCIONES_INSERTAR_SP;
----
PROCEDURE TAJO_DEDUCCIONES_MODIFICAR_SP (
    P_ID_DEDUCCION IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.ID_DEDUCCION%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.NOMBRE%TYPE,
    P_PORCENTAJE_NUEVO IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.PORCENTAJE%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_DEDUCCIONES_TB
    SET NOMBRE = P_NOMBRE_NUEVO,
        PORCENTAJE = P_PORCENTAJE_NUEVO
    WHERE ID_DEDUCCION = P_ID_DEDUCCION;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID ' || P_ID_DEDUCCION || ' NO EXISTE EN LA TABLA.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO TIENEN EL FORMATO CORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_DEDUCCIONES_MODIFICAR_SP;
----
PROCEDURE TAJO_DEDUCCIONES_ELIMINAR_SP (
    P_ID_DEDUCCION IN TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.ID_DEDUCCION%TYPE
) IS
    V_ID_DEDUCCION TAJO_PROYECTO.TAJO_DEDUCCIONES_TB.ID_DEDUCCION%TYPE;
BEGIN
    SELECT ID_DEDUCCION INTO V_ID_DEDUCCION
    FROM TAJO_PROYECTO.TAJO_DEDUCCIONES_TB
    WHERE ID_DEDUCCION = P_ID_DEDUCCION;

    UPDATE TAJO_PROYECTO.TAJO_DEDUCCIONES_TB
    SET ID_ESTADO = 2 -- Inactivo
    WHERE ID_DEDUCCION = P_ID_DEDUCCION;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO CON EL ID: ' || P_ID_DEDUCCION || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ NINGÚN REGISTRO CON EL ID ' || P_ID_DEDUCCION);
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID PROPORCIONADO TIENE UN FORMATO NO VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_DEDUCCIONES_ELIMINAR_SP;

---PROCEDIMIENTOS DE DESCUENTOS
PROCEDURE TAJO_DESCUENTOS_INSERTAR_SP (
    P_ID_DESCUENTO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.ID_DESCUENTO%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.NOMBRE%TYPE,
    P_PORCENTAJE IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.PORCENTAJE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_DESCUENTOS_TB (ID_DESCUENTO, NOMBRE, PORCENTAJE, ID_ESTADO)
    VALUES (P_ID_DESCUENTO, P_NOMBRE, P_PORCENTAJE, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID ' || P_ID_DESCUENTO || ' YA SE ENCUENTRA REGISTRADO.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO O SUPERA EL TAMAÑO PERMITIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_DESCUENTOS_INSERTAR_SP;
----
PROCEDURE TAJO_DESCUENTOS_MODIFICAR_SP (
    P_ID_DESCUENTO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.ID_DESCUENTO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.NOMBRE%TYPE,
    P_PORCENTAJE_NUEVO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.PORCENTAJE%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_DESCUENTOS_TB
    SET NOMBRE = P_NOMBRE_NUEVO,
        PORCENTAJE = P_PORCENTAJE_NUEVO
    WHERE ID_DESCUENTO = P_ID_DESCUENTO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID ' || P_ID_DESCUENTO || ' NO EXISTE EN LA TABLA.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO TIENEN EL FORMATO CORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_DESCUENTOS_MODIFICAR_SP;
----
PROCEDURE TAJO_DESCUENTOS_ELIMINAR_SP (
    P_ID_DESCUENTO IN TAJO_PROYECTO.TAJO_DESCUENTOS_TB.ID_DESCUENTO%TYPE
) IS
    V_ID_DESCUENTO TAJO_PROYECTO.TAJO_DESCUENTOS_TB.ID_DESCUENTO%TYPE;
BEGIN
    SELECT ID_DESCUENTO INTO V_ID_DESCUENTO
    FROM TAJO_PROYECTO.TAJO_DESCUENTOS_TB
    WHERE ID_DESCUENTO = P_ID_DESCUENTO;

    UPDATE TAJO_PROYECTO.TAJO_DESCUENTOS_TB
    SET ID_ESTADO = 2 -- Inactivo
    WHERE ID_DESCUENTO = P_ID_DESCUENTO;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO CON EL ID: ' || P_ID_DESCUENTO || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ NINGÚN REGISTRO CON EL ID ' || P_ID_DESCUENTO);
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID PROPORCIONADO TIENE UN FORMATO NO VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_DESCUENTOS_ELIMINAR_SP;

----PROCEDIMIENTOS DE DETALLE VENTAS
PROCEDURE TAJO_DETALLE_VENTAS_INSERTAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_VENTA%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_MATERIAL%TYPE,
    P_PRECIO_TOTAL IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.PRECIO_TOTAL%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB (ID_VENTA, ID_MATERIAL, PRECIO_TOTAL, ID_ESTADO)
    VALUES (P_ID_VENTA, P_ID_MATERIAL, P_PRECIO_TOTAL, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE DETALLE DE VENTA INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL DETALLE PARA ESTA VENTA Y MATERIAL YA EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO EN EL DETALLE DE VENTA.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_DETALLE_VENTAS_INSERTAR_SP;
----
PROCEDURE TAJO_DETALLE_VENTAS_MODIFICAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_VENTA%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_MATERIAL%TYPE,
    P_PRECIO_NUEVO IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.PRECIO_TOTAL%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB
    SET PRECIO_TOTAL = P_PRECIO_NUEVO
    WHERE ID_VENTA = P_ID_VENTA 
      AND ID_MATERIAL = P_ID_MATERIAL;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DETALLE DE VENTA MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ EL DETALLE PARA LA VENTA ' || P_ID_VENTA);

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO SON VÁLIDOS.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_DETALLE_VENTAS_MODIFICAR_SP;
----
PROCEDURE TAJO_DETALLE_VENTAS_ELIMINAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_VENTA%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_MATERIAL%TYPE
) IS
    V_ID_VENTA TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB.ID_VENTA%TYPE;
BEGIN
    SELECT ID_VENTA INTO V_ID_VENTA
    FROM TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB
    WHERE ID_VENTA = P_ID_VENTA 
      AND ID_MATERIAL = P_ID_MATERIAL;

    UPDATE TAJO_PROYECTO.TAJO_DETALLE_VENTAS_TB
    SET ID_ESTADO = 2 -- Inactivo
    WHERE ID_VENTA = P_ID_VENTA 
      AND ID_MATERIAL = P_ID_MATERIAL;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DETALLE ELIMINADO (INACTIVO) PARA VENTA: ' || P_ID_VENTA);
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ EL REGISTRO PARA ELIMINAR.');
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL FORMATO DE LOS IDS NO ES VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_DETALLE_VENTAS_ELIMINAR_SP;

---PROCEDIMIENTOS DE ESTADOS
PROCEDURE TAJO_ESTADOS_INSERTAR_SP (
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.ID_ESTADO%TYPE,
    P_NOMBRE_ESTADO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.NOMBRE_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_ESTADOS_TB (ID_ESTADO, NOMBRE_ESTADO)
    VALUES (P_ID_ESTADO, P_NOMBRE_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE ESTADO INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE ESTADO ' || P_ID_ESTADO || ' YA SE ENCUENTRA REGISTRADO.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO EN EL NOMBRE DEL ESTADO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_ESTADOS_INSERTAR_SP;
----
PROCEDURE TAJO_ESTADOS_MODIFICAR_SP (
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.ID_ESTADO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.NOMBRE_ESTADO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_ESTADOS_TB
    SET NOMBRE_ESTADO = P_NOMBRE_NUEVO
    WHERE ID_ESTADO = P_ID_ESTADO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE ESTADO MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE ESTADO ' || P_ID_ESTADO || ' NO EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL NOMBRE INGRESADO NO TIENE EL FORMATO CORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_ESTADOS_MODIFICAR_SP;
---
PROCEDURE TAJO_ESTADOS_ELIMINAR_SP (
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_ESTADOS_TB.ID_ESTADO%TYPE
) IS
    V_ID_ESTADO TAJO_PROYECTO.TAJO_ESTADOS_TB.ID_ESTADO%TYPE;
BEGIN
    SELECT ID_ESTADO INTO V_ID_ESTADO
    FROM TAJO_PROYECTO.TAJO_ESTADOS_TB
    WHERE ID_ESTADO = P_ID_ESTADO;

    -- Aquí podrías tener una lógica para marcarlo como "Deshabilitado" 
    -- si tuvieras una columna de estado propio, si no, se deja la estructura:
    UPDATE TAJO_PROYECTO.TAJO_ESTADOS_TB
    SET NOMBRE_ESTADO = NOMBRE_ESTADO || ' (INACTIVO)'
    WHERE ID_ESTADO = P_ID_ESTADO;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('ESTADO CON ID: ' || P_ID_ESTADO || ' MARCADO COMO INACTIVO');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ EL ESTADO CON EL ID ' || P_ID_ESTADO);
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID PROPORCIONADO NO ES VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_ESTADOS_ELIMINAR_SP;

----PROCEDIMIENTOS DE EXTRACCIONES
PROCEDURE TAJO_EXTRACCIONES_INSERTAR_SP (
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_EXTRACCION%TYPE,
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.IDENTIFICACION%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_MATERIAL%TYPE,
    P_FECHA_EXTRACCION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.FECHA_EXTRACCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_EXTRACCIONES_TB (
        ID_EXTRACCION, IDENTIFICACION, ID_MATERIAL, FECHA_EXTRACCION, ID_ESTADO
    )
    VALUES (
        P_ID_EXTRACCION, P_IDENTIFICACION, P_ID_MATERIAL, P_FECHA_EXTRACCION, P_ID_ESTADO
    );
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE EXTRACCIÓN INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE EXTRACCIÓN ' || P_ID_EXTRACCION || ' YA EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO EN LOS CAMPOS DE EXTRACCIÓN.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_EXTRACCIONES_INSERTAR_SP;
----
PROCEDURE TAJO_EXTRACCIONES_MODIFICAR_SP (
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_EXTRACCION%TYPE,
    P_IDENTIFICACION_NUEVA IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.IDENTIFICACION%TYPE,
    P_ID_MATERIAL_NUEVO IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_MATERIAL%TYPE,
    P_FECHA_NUEVA IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.FECHA_EXTRACCION%TYPE,
    P_ID_ESTADO_NUEVO IN NUMBER
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_EXTRACCIONES_TB
    SET IDENTIFICACION = P_IDENTIFICACION_NUEVA,
        ID_MATERIAL = P_ID_MATERIAL_NUEVO,
        FECHA_EXTRACCION = P_FECHA_NUEVA,
        ID_ESTADO = P_ID_ESTADO_NUEVO
    WHERE ID_EXTRACCION = P_ID_EXTRACCION;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE EXTRACCION MODIFICADO EXITOSAMENTE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA EXTRACCION CON ID ' || P_ID_EXTRACCION || ' NO EXISTE.');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS TIENEN UN FORMATO INCORRECTO.');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_EXTRACCIONES_MODIFICAR_SP;
----
PROCEDURE TAJO_EXTRACCIONES_ELIMINAR_SP (
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_EXTRACCION%TYPE
) IS
    V_ID_EXTRACCION TAJO_PROYECTO.TAJO_EXTRACCIONES_TB.ID_EXTRACCION%TYPE;
BEGIN
    SELECT ID_EXTRACCION INTO V_ID_EXTRACCION
    FROM TAJO_PROYECTO.TAJO_EXTRACCIONES_TB
    WHERE ID_EXTRACCION = P_ID_EXTRACCION;

    UPDATE TAJO_PROYECTO.TAJO_EXTRACCIONES_TB
    SET ID_ESTADO = 2 -- Estado Inactivo
    WHERE ID_EXTRACCION = P_ID_EXTRACCION;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('EXTRACCIÓN CON ID: ' || P_ID_EXTRACCION || ' ELIMINADA (INACTIVA)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ LA EXTRACCIÓN CON EL ID ' || P_ID_EXTRACCION);
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE EXTRACCIÓN PROPORCIONADO NO ES VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_EXTRACCIONES_ELIMINAR_SP;

----PROCEDIMIENTOS DE FACTURACION
PROCEDURE TAJO_FACTURACION_INSERTAR_SP (
    P_ID_FACTURA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_FACTURA%TYPE,
    P_CEDULA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.CEDULA%TYPE,
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_VENTA%TYPE,
    P_ID_IMPUESTO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_IMPUESTO%TYPE,
    P_ID_DESCUENTO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_DESCUENTO%TYPE,
    P_ID_METODO_PAGO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_METODO_PAGO%TYPE,
    P_FECHA_EMISION IN TAJO_PROYECTO.TAJO_FACTURACION_TB.FECHA_EMISION%TYPE,
    P_MONTO_TOTAL IN TAJO_PROYECTO.TAJO_FACTURACION_TB.MONTO_TOTAL%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_FACTURACION_TB (
        ID_FACTURA, CEDULA, ID_VENTA, ID_IMPUESTO, ID_DESCUENTO, 
        ID_METODO_PAGO, FECHA_EMISION, MONTO_TOTAL, ID_ESTADO)
    VALUES (
        P_ID_FACTURA, P_CEDULA, P_ID_VENTA, P_ID_IMPUESTO, P_ID_DESCUENTO, 
        P_ID_METODO_PAGO, P_FECHA_EMISION, P_MONTO_TOTAL, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE FACTURA INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE FACTURA ' || P_ID_FACTURA || ' YA EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS DE LA FACTURA TIENEN UN FORMATO INCORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_FACTURACION_INSERTAR_SP;
----
PROCEDURE TAJO_FACTURACION_MODIFICAR_SP (
    P_ID_FACTURA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_FACTURA%TYPE,
    P_ID_METODO_PAGO_NUEVO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_METODO_PAGO%TYPE,
    P_MONTO_NUEVO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.MONTO_TOTAL%TYPE,
    P_ID_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_ESTADO%TYPE -- ¡AQUI ESTÁ LA MAGIA!
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_FACTURACION_TB
    SET ID_METODO_PAGO = P_ID_METODO_PAGO_NUEVO,
        MONTO_TOTAL = P_MONTO_NUEVO,
        ID_ESTADO = P_ID_ESTADO_NUEVO
    WHERE ID_FACTURA = P_ID_FACTURA;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE FACTURA MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
    WHEN VALUE_ERROR THEN ROLLBACK;
    WHEN OTHERS THEN ROLLBACK;
END TAJO_FACTURACION_MODIFICAR_SP;
----
PROCEDURE TAJO_FACTURACION_ELIMINAR_SP (
    P_ID_FACTURA IN TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_FACTURA%TYPE
) IS
    V_ID_FACTURA TAJO_PROYECTO.TAJO_FACTURACION_TB.ID_FACTURA%TYPE;
BEGIN
    SELECT ID_FACTURA INTO V_ID_FACTURA
    FROM TAJO_PROYECTO.TAJO_FACTURACION_TB
    WHERE ID_FACTURA = P_ID_FACTURA;

    UPDATE TAJO_PROYECTO.TAJO_FACTURACION_TB
    SET ID_ESTADO = 2 -- Estado Anulado/Inactivo
    WHERE ID_FACTURA = P_ID_FACTURA;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('FACTURA CON ID: ' || P_ID_FACTURA || ' ANULADA CORRECTAMENTE');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ LA FACTURA CON EL ID ' || P_ID_FACTURA);
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE FACTURA PROPORCIONADO NO ES VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_FACTURACION_ELIMINAR_SP;

----PROCEDIMIENTOS DE IMPUESTOS
PROCEDURE TAJO_IMPUESTOS_INSERTAR_SP (
    P_ID_IMPUESTO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.ID_IMPUESTO%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.NOMBRE%TYPE,
    P_PORCENTAJE IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.PORCENTAJE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_IMPUESTOS_TB (ID_IMPUESTO, NOMBRE, PORCENTAJE, ID_ESTADO)
    VALUES (P_ID_IMPUESTO, P_NOMBRE, P_PORCENTAJE, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE IMPUESTO INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE IMPUESTO ' || P_ID_IMPUESTO || ' YA EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO EN EL IMPUESTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_IMPUESTOS_INSERTAR_SP;
----
PROCEDURE TAJO_IMPUESTOS_MODIFICAR_SP (
    P_ID_IMPUESTO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.ID_IMPUESTO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.NOMBRE%TYPE,
    P_PORCENTAJE_NUEVO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.PORCENTAJE%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_IMPUESTOS_TB
    SET NOMBRE = P_NOMBRE_NUEVO,
        PORCENTAJE = P_PORCENTAJE_NUEVO
    WHERE ID_IMPUESTO = P_ID_IMPUESTO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE IMPUESTO MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE IMPUESTO ' || P_ID_IMPUESTO || ' NO EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO TIENEN EL FORMATO CORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_IMPUESTOS_MODIFICAR_SP;
-----
PROCEDURE TAJO_IMPUESTOS_ELIMINAR_SP (
    P_ID_IMPUESTO IN TAJO_PROYECTO.TAJO_IMPUESTOS_TB.ID_IMPUESTO%TYPE
) IS
    V_ID_IMPUESTO TAJO_PROYECTO.TAJO_IMPUESTOS_TB.ID_IMPUESTO%TYPE;
BEGIN
    SELECT ID_IMPUESTO INTO V_ID_IMPUESTO
    FROM TAJO_PROYECTO.TAJO_IMPUESTOS_TB
    WHERE ID_IMPUESTO = P_ID_IMPUESTO;

    UPDATE TAJO_PROYECTO.TAJO_IMPUESTOS_TB
    SET ID_ESTADO = 2 -- Inactivo
    WHERE ID_IMPUESTO = P_ID_IMPUESTO;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('IMPUESTO CON ID: ' || P_ID_IMPUESTO || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ NINGÚN IMPUESTO CON EL ID ' || P_ID_IMPUESTO);
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID PROPORCIONADO NO ES VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_IMPUESTOS_ELIMINAR_SP;

----PROCEDIMIENTOS DE INVENTARIO
PROCEDURE TAJO_INVENTARIO_INSERTAR_SP (
    P_ID_INVENTARIO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_INVENTARIO%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.CANTIDAD_MATERIAL%TYPE,
    P_NIVEL_STOCK IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.NIVEL_STOCK%TYPE,
    P_ID_TIPO_MOV IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO_INVENTARIO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_INVENTARIO_TB (
        ID_INVENTARIO, ID_MATERIAL, CANTIDAD_MATERIAL, 
        NIVEL_STOCK, ID_TIPO_MOVIMIENTO_INVENTARIO, ID_ESTADO)
    VALUES (
        P_ID_INVENTARIO, P_ID_MATERIAL, P_CANTIDAD, 
        P_NIVEL_STOCK, P_ID_TIPO_MOV, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE INVENTARIO INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE INVENTARIO ' || P_ID_INVENTARIO || ' YA EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO EN EL INVENTARIO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_INVENTARIO_INSERTAR_SP;
-----
PROCEDURE TAJO_INVENTARIO_MODIFICAR_SP (
    P_ID_INVENTARIO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_INVENTARIO%TYPE,
    P_CANTIDAD_NUEVA IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.CANTIDAD_MATERIAL%TYPE,
    P_STOCK_NUEVO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.NIVEL_STOCK%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_INVENTARIO_TB
    SET CANTIDAD_MATERIAL = P_CANTIDAD_NUEVA,
        NIVEL_STOCK = P_STOCK_NUEVO
    WHERE ID_INVENTARIO = P_ID_INVENTARIO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('INVENTARIO MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE INVENTARIO ' || P_ID_INVENTARIO || ' NO EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO SON VÁLIDOS.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_INVENTARIO_MODIFICAR_SP;
----
PROCEDURE TAJO_INVENTARIO_ELIMINAR_SP (
    P_ID_INVENTARIO IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_INVENTARIO%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_MATERIAL%TYPE
) IS
    V_ID_INVENTARIO TAJO_PROYECTO.TAJO_INVENTARIO_TB.ID_INVENTARIO%TYPE;
BEGIN
    SELECT ID_INVENTARIO INTO V_ID_INVENTARIO
    FROM TAJO_PROYECTO.TAJO_INVENTARIO_TB
    WHERE ID_INVENTARIO = P_ID_INVENTARIO 
      AND ID_MATERIAL = P_ID_MATERIAL;

    UPDATE TAJO_PROYECTO.TAJO_INVENTARIO_TB
    SET ID_ESTADO = 2 -- Inactivo
    WHERE ID_INVENTARIO = P_ID_INVENTARIO 
      AND ID_MATERIAL = P_ID_MATERIAL;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('INVENTARIO ' || P_ID_INVENTARIO || ' CON MATERIAL ' || P_ID_MATERIAL || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ EL REGISTRO DE INVENTARIO PARA ELIMINAR.');
    
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL FORMATO DE LOS IDS NO ES VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_INVENTARIO_ELIMINAR_SP;

---PROCEDIMIENTOS DE LA TABLA MANTENIMIENTOS
PROCEDURE TAJO_MANTENIMIENTO_INSERTAR_SP (
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_DESCRIPCION IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB (ID_MANTENIMIENTO, DESCRIPCION, ID_ESTADO)
    VALUES (P_ID_MANTENIMIENTO, P_DESCRIPCION, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE MANTENIMIENTO INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE MANTENIMIENTO ' || P_ID_MANTENIMIENTO || ' YA EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO NO VÁLIDO EN LA DESCRIPCIÓN.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MANTENIMIENTO_INSERTAR_SP;
-----
PROCEDURE TAJO_MANTENIMIENTO_MODIFICAR_SP (
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_DESCRIPCION_NUEVA IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.DESCRIPCION%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB
    SET DESCRIPCION = P_DESCRIPCION_NUEVA
    WHERE ID_MANTENIMIENTO = P_ID_MANTENIMIENTO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MANTENIMIENTO MODIFICADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE MANTENIMIENTO ' || P_ID_MANTENIMIENTO || ' NO EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA DESCRIPCIÓN EXCEDE EL TAMAÑO O ES INVÁLIDA.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MANTENIMIENTO_MODIFICAR_SP;
-----
PROCEDURE TAJO_MANTENIMIENTO_ELIMINAR_SP (
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE
) IS
    V_ID_MANTENIMIENTO TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE;
BEGIN
    
    SELECT ID_MANTENIMIENTO INTO V_ID_MANTENIMIENTO
    FROM TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB
    WHERE ID_MANTENIMIENTO = P_ID_MANTENIMIENTO;

    UPDATE TAJO_PROYECTO.TAJO_MANTENIMIENTO_TB
    SET ID_ESTADO = 2 -- Inactivo
    WHERE ID_MANTENIMIENTO = P_ID_MANTENIMIENTO;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MANTENIMIENTO ' || P_ID_MANTENIMIENTO || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ EL REGISTRO PARA ELIMINAR.');
    
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MANTENIMIENTO_ELIMINAR_SP;

----PROCEDIMIENTOS DE LA TABLA DE TAJO_MAQUINARIA_EXTRACCIONES_TB
PROCEDURE TAJO_MAQUINARIA_EXTRACCION_INSERTAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.PLACA%TYPE,
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_EXTRACCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB (PLACA, ID_EXTRACCION, ID_ESTADO)
    VALUES (P_PLACA, P_ID_EXTRACCION, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('ASOCIACIÓN MAQUINARIA EXTRACCIÓN INSERTADA CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ESTA PLACA YA ESTÁ ASOCIADA A ESTA EXTRACCIÓN.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL FORMATO DE LA PLACA O EL ID NO ES VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MAQUINARIA_EXTRACCION_INSERTAR_SP;
----
PROCEDURE TAJO_MAQUINARIA_EXTRACCION_MODIFICAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.PLACA%TYPE,
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_EXTRACCION%TYPE,
    P_ID_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB
    SET ID_ESTADO = P_ID_ESTADO_NUEVO
    WHERE PLACA = P_PLACA 
      AND ID_EXTRACCION = P_ID_EXTRACCION;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('ESTADO DE LA ASOCIACIÓN ACTUALIZADO EXITOSAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ LA ASOCIACIÓN PARA MODIFICAR.');
        
     WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO SON VÁLIDOS.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MAQUINARIA_EXTRACCION_MODIFICAR_SP;
----
PROCEDURE TAJO_MAQUINARIA_EXTRACCION_ELIMINAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.PLACA%TYPE,
    P_ID_EXTRACCION IN TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.ID_EXTRACCION%TYPE
) IS
    V_PLACA TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB.PLACA%TYPE;
BEGIN

    SELECT PLACA INTO V_PLACA
    FROM TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB
    WHERE PLACA = P_PLACA 
      AND ID_EXTRACCION = P_ID_EXTRACCION;

    UPDATE TAJO_PROYECTO.TAJO_MAQUINARIA_EXTRACCION_TB
    SET ID_ESTADO = 2 -- Inactivo
    WHERE PLACA = P_PLACA 
      AND ID_EXTRACCION = P_ID_EXTRACCION;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('ASOCIACIÓN CON PLACA ' || P_PLACA || ' ELIMINADA (INACTIVA)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ EL REGISTRO PARA ELIMINAR.');
        
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL FORMATO DE LOS IDS NO ES VÁLIDO.');
    
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MAQUINARIA_EXTRACCION_ELIMINAR_SP;

----PROCEDIMIENTOS DE LA TABLA TAJO_MAQUINARIA_MANTENIMIENTO_TB
PROCEDURE TAJO_MAQUINARIA_MANTENIMIENTO_INSERTAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.PLACA%TYPE,
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_FECHA_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.FECHA_MANTENIMIENTO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_ESTADO%TYPE
) IS 
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB (
        PLACA, ID_MANTENIMIENTO, FECHA_MANTENIMIENTO, ID_ESTADO)
    VALUES (
        P_PLACA, P_ID_MANTENIMIENTO, P_FECHA_MANTENIMIENTO, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE MAQUINARIA MANTENIMIENTO INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: YA EXISTE UN REGISTRO PARA ESTA PLACA, MANTENIMIENTO Y FECHA.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL FORMATO DE LOS DATOS INGRESADOS NO ES VÁLIDO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MAQUINARIA_MANTENIMIENTO_INSERTAR_SP;
----
PROCEDURE TAJO_MAQUINARIA_MANTENIMIENTO_MODIFICAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.PLACA%TYPE,
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_FECHA_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.FECHA_MANTENIMIENTO%TYPE,
    P_ID_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB
    SET ID_ESTADO = P_ID_ESTADO_NUEVO
    WHERE PLACA = P_PLACA 
      AND ID_MANTENIMIENTO = P_ID_MANTENIMIENTO
      AND FECHA_MANTENIMIENTO = P_FECHA_MANTENIMIENTO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('ESTADO DEL MANTENIMIENTO DE MAQUINARIA ACTUALIZADO');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ EL REGISTRO PARA MODIFICAR.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MAQUINARIA_MANTENIMIENTO_MODIFICAR_SP;
----
PROCEDURE TAJO_MAQUINARIA_MANTENIMIENTO_ELIMINAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.PLACA%TYPE,
    P_ID_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.ID_MANTENIMIENTO%TYPE,
    P_FECHA_MANTENIMIENTO IN TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.FECHA_MANTENIMIENTO%TYPE
) IS
    V_PLACA TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB.PLACA%TYPE;
BEGIN
    SELECT PLACA INTO V_PLACA
    FROM TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB
    WHERE PLACA = P_PLACA 
      AND ID_MANTENIMIENTO = P_ID_MANTENIMIENTO
      AND FECHA_MANTENIMIENTO = P_FECHA_MANTENIMIENTO;

    UPDATE TAJO_PROYECTO.TAJO_MAQUINARIA_MANTENIMIENTO_TB
    SET ID_ESTADO = 2 -- Inactivo
    WHERE PLACA = P_PLACA 
      AND ID_MANTENIMIENTO = P_ID_MANTENIMIENTO
      AND FECHA_MANTENIMIENTO = P_FECHA_MANTENIMIENTO;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MANTENIMIENTO DE PLACA ' || P_PLACA || ' ELIMINADO (INACTIVO)');
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRÓ EL REGISTRO ESPECÍFICO PARA ELIMINAR.');
    
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MAQUINARIA_MANTENIMIENTO_ELIMINAR_SP;

----PROCEDIMIENTOS DE TABLA DE MAQUINARIA
PROCEDURE TAJO_MAQUINARIA_INSERTAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.PLACA%TYPE,
    P_MODELO IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.MODELO%TYPE,
    P_HORAS_TRABAJADAS IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.HORAS_TRABAJADAS%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_MAQUINARIA_TB (
        PLACA, MODELO, HORAS_TRABAJADAS, ID_ESTADO)
    VALUES (
        P_PLACA, P_MODELO, P_HORAS_TRABAJADAS, P_ID_ESTADO);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MAQUINARIA INSERTADA CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA PLACA ' || P_PLACA || ' YA EXISTE.');

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO INCORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MAQUINARIA_INSERTAR_SP;
-----
PROCEDURE TAJO_MAQUINARIA_MODIFICAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.PLACA%TYPE,
    P_MODELO_NUEVO IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.MODELO%TYPE,
    P_HORAS_NUEVAS IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.HORAS_TRABAJADAS%TYPE,
    P_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_MAQUINARIA_TB
    SET MODELO = P_MODELO_NUEVO,
        HORAS_TRABAJADAS = P_HORAS_NUEVAS,
        ID_ESTADO = P_ESTADO_NUEVO
    WHERE PLACA = P_PLACA;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MAQUINARIA MODIFICADA CORRECTAMENTE');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO EXISTE LA PLACA ' || P_PLACA);

    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INCORRECTO.');

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MAQUINARIA_MODIFICAR_SP;

---ELIMINAR---
PROCEDURE TAJO_MAQUINARIA_ELIMINAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_MAQUINARIA_TB.PLACA%TYPE
) IS
    V_PLACA TAJO_PROYECTO.TAJO_MAQUINARIA_TB.PLACA%TYPE;
BEGIN
    SELECT PLACA INTO V_PLACA
    FROM TAJO_PROYECTO.TAJO_MAQUINARIA_TB
    WHERE PLACA = P_PLACA;

    UPDATE TAJO_PROYECTO.TAJO_MAQUINARIA_TB
    SET ID_ESTADO = 2
    WHERE PLACA = P_PLACA;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MAQUINARIA ' || P_PLACA || ' ELIMINADA (INACTIVA)');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO EXISTE LA PLACA ' || P_PLACA);

    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR INESPERADO: ' || SQLERRM);
END TAJO_MAQUINARIA_ELIMINAR_SP;


-----PROCEDIMIENTOS DE LA TABLA DE MATERIALES

PROCEDURE TAJO_MATERIALES_INSERTAR_SP (
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_MATERIAL%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_MATERIALES_TB.NOMBRE%TYPE,
    P_UNIDAD_MEDIDA IN TAJO_PROYECTO.TAJO_MATERIALES_TB.UNIDAD_MEDIDA%TYPE,
    P_FUNCION IN TAJO_PROYECTO.TAJO_MATERIALES_TB.FUNCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_MATERIALES_TB (
        ID_MATERIAL, NOMBRE, UNIDAD_MEDIDA, FUNCION, ID_ESTADO)
    VALUES (
        P_ID_MATERIAL, P_NOMBRE, P_UNIDAD_MEDIDA, P_FUNCION, P_ID_ESTADO);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MATERIAL INSERTADO CORRECTAMENTE');

EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL MATERIAL YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INCORRECTO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END TAJO_MATERIALES_INSERTAR_SP;


-- MODIFICAR
PROCEDURE TAJO_MATERIALES_MODIFICAR_SP (
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_MATERIAL%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_MATERIALES_TB.NOMBRE%TYPE,
    P_UNIDAD_NUEVA IN TAJO_PROYECTO.TAJO_MATERIALES_TB.UNIDAD_MEDIDA%TYPE,
    P_FUNCION_NUEVA IN TAJO_PROYECTO.TAJO_MATERIALES_TB.FUNCION%TYPE,
    P_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_ESTADO%TYPE -- <--- AGREGAR ESTO
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_MATERIALES_TB
    SET NOMBRE        = P_NOMBRE_NUEVO,
        UNIDAD_MEDIDA = P_UNIDAD_NUEVA,
        FUNCION       = P_FUNCION_NUEVA,
        ID_ESTADO     = P_ESTADO_NUEVO -- <--- Y ESTO
    WHERE ID_MATERIAL = P_ID_MATERIAL;

    COMMIT;
END TAJO_MATERIALES_MODIFICAR_SP;

-- ELIMINAR (LÓGICO)
PROCEDURE TAJO_MATERIALES_ELIMINAR_SP (
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_MATERIAL%TYPE
) IS
    V_ID_MATERIAL TAJO_PROYECTO.TAJO_MATERIALES_TB.ID_MATERIAL%TYPE;
BEGIN
    SELECT ID_MATERIAL INTO V_ID_MATERIAL
    FROM TAJO_PROYECTO.TAJO_MATERIALES_TB
    WHERE ID_MATERIAL = P_ID_MATERIAL;

    UPDATE TAJO_PROYECTO.TAJO_MATERIALES_TB
    SET ID_ESTADO = 2
    WHERE ID_MATERIAL = P_ID_MATERIAL;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MATERIAL ELIMINADO (INACTIVO)');

EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: MATERIAL NO EXISTE');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END TAJO_MATERIALES_ELIMINAR_SP;

-----PROCEDIMIENTOS DE LA TABLA DE METODO DE PAGO
PROCEDURE TAJO_METODO_PAGO_INSERTAR_SP (
    P_ID_METODO_PAGO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
    P_NOMBRE IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.NOMBRE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_METODO_PAGO_TB(ID_METODO_PAGO, NOMBRE, ID_ESTADO)
    VALUES(P_ID_METODO_PAGO, P_NOMBRE, P_ID_ESTADO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('METODO DE PAGO INSERTADO CORRECTAMENTE');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL METODO DE PAGO YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INCORRECTO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_METODO_PAGO_INSERTAR_SP;
----
PROCEDURE TAJO_METODO_PAGO_MODIFICAR_SP (
    P_ID_METODO_PAGO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.ID_METODO_PAGO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.NOMBRE%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_METODO_PAGO_TB 
    SET NOMBRE = P_NOMBRE_NUEVO 
    WHERE ID_METODO_PAGO = P_ID_METODO_PAGO;
    
    IF SQL%NOTFOUND THEN 
    RAISE NO_DATA_FOUND; 
    END IF;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('METODO DE PAGO MODIFICADO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: METODO DE PAGO NO EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR FORMATO INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_METODO_PAGO_MODIFICAR_SP;
----
PROCEDURE TAJO_METODO_PAGO_ELIMINAR_SP (
    P_ID_METODO_PAGO IN TAJO_PROYECTO.TAJO_METODO_PAGO_TB.ID_METODO_PAGO%TYPE
) IS
    V_ID_METODO_PAGO TAJO_PROYECTO.TAJO_METODO_PAGO_TB.ID_METODO_PAGO%TYPE;
BEGIN
    SELECT ID_METODO_PAGO INTO V_ID_METODO_PAGO 
    FROM TAJO_PROYECTO.TAJO_METODO_PAGO_TB 
    WHERE ID_METODO_PAGO = P_ID_METODO_PAGO;
    
    UPDATE TAJO_PROYECTO.TAJO_METODO_PAGO_TB 
    SET ID_ESTADO = 2 
    WHERE ID_METODO_PAGO = P_ID_METODO_PAGO;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('METODO DE PAGO ELIMINADO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: METODO DE PAGO NO EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR FORMATO INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_METODO_PAGO_ELIMINAR_SP;

---PROCEDIMIENTOS DE LA TABLA DE PAGO USUARIOS
PROCEDURE TAJO_PAGOS_USUARIOS_INSERTAR_SP (
    P_ID_PAGO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_PAGO%TYPE,
    P_ID_PLANILLA IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_PLANILLA%TYPE,
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.IDENTIFICACION%TYPE,
    P_SALARIO_BASE IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.SALARIO_BASE%TYPE,
    P_ID_DEDUCCION IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_DEDUCCION%TYPE,
    P_ID_BONIFICACION IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_BONIFICACION%TYPE,
    P_SALARIO_NETO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.SALARIO_NETO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB (
        ID_PAGO, ID_PLANILLA, IDENTIFICACION, SALARIO_BASE, 
        ID_DEDUCCION, ID_BONIFICACION, SALARIO_NETO, ID_ESTADO)
    VALUES (
        P_ID_PAGO, P_ID_PLANILLA, P_IDENTIFICACION, P_SALARIO_BASE, 
        P_ID_DEDUCCION, P_ID_BONIFICACION, P_SALARIO_NETO, P_ID_ESTADO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('PAGO DE USUARIO INSERTADO CORRECTAMENTE');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL PAGO YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INCORRECTO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_PAGOS_USUARIOS_INSERTAR_SP;
------

PROCEDURE TAJO_PAGOS_USUARIOS_MODIFICAR_SP (
    P_ID_PAGO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_PAGO%TYPE,
    P_SALARIO_BASE_NUEVO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.SALARIO_BASE%TYPE,
    P_SALARIO_NETO_NUEVO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.SALARIO_NETO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB
    SET SALARIO_BASE = P_SALARIO_BASE_NUEVO,
        SALARIO_NETO = P_SALARIO_NETO_NUEVO
    WHERE ID_PAGO = P_ID_PAGO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('PAGO DE USUARIO MODIFICADO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: PAGO NO EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR FORMATO INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_PAGOS_USUARIOS_MODIFICAR_SP;
-----
PROCEDURE TAJO_PAGOS_USUARIOS_ELIMINAR_SP (
    P_ID_PAGO IN TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_PAGO%TYPE
) IS
    V_ID_PAGO TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB.ID_PAGO%TYPE;
BEGIN
    SELECT ID_PAGO INTO V_ID_PAGO 
    FROM TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB 
    WHERE ID_PAGO = P_ID_PAGO;

    UPDATE TAJO_PROYECTO.TAJO_PAGOS_USUARIOS_TB
    SET ID_ESTADO = 2
    WHERE ID_PAGO = P_ID_PAGO;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('PAGO DE USUARIO ELIMINADO (BORRADO LOGICO)');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL PAGO ESPECIFICADO NO EXISTE');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_PAGOS_USUARIOS_ELIMINAR_SP;

----PROCEDIMIENTOS DE LA TABLA DE TAJO_PLANILLAS_TB
PROCEDURE TAJO_PLANILLAS_INSERTAR_SP (
    P_ID_PLANILLA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.ID_PLANILLA%TYPE,
    P_DESCRIPCION IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.DESCRIPCION%TYPE,
    P_FECHA_INICIO IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_INICIO%TYPE,
    P_FECHA_FINAL IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_FINAL%TYPE,
    P_FECHA_PAGO IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_PAGO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_PLANILLAS_TB (
        ID_PLANILLA, DESCRIPCION, FECHA_INICIO, FECHA_FINAL, FECHA_PAGO, ID_ESTADO)
    VALUES (P_ID_PLANILLA, P_DESCRIPCION, P_FECHA_INICIO, P_FECHA_FINAL, P_FECHA_PAGO, P_ID_ESTADO);
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('PLANILLA CREADA EXITOSAMENTE');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE PLANILLA YA EXISTE');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_PLANILLAS_INSERTAR_SP;
-----
PROCEDURE TAJO_PLANILLAS_MODIFICAR_SP (
    P_ID_PLANILLA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.ID_PLANILLA%TYPE,
    P_DESCRIPCION_NUEVA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.DESCRIPCION%TYPE,
    P_FECHA_INICIO_NUEVA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_INICIO%TYPE,
    P_FECHA_FINAL_NUEVA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_FINAL%TYPE,
    P_FECHA_PAGO_NUEVA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.FECHA_PAGO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_PLANILLAS_TB
    SET DESCRIPCION = P_DESCRIPCION_NUEVA,
        FECHA_INICIO = P_FECHA_INICIO_NUEVA,
        FECHA_FINAL = P_FECHA_FINAL_NUEVA,
        FECHA_PAGO = P_FECHA_PAGO_NUEVA
    WHERE ID_PLANILLA = P_ID_PLANILLA;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('PLANILLA MODIFICADA');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: PLANILLA NO EXISTE');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_PLANILLAS_MODIFICAR_SP;

-- ELIMINAR PLANILLA
PROCEDURE TAJO_PLANILLAS_ELIMINAR_SP (
    P_ID_PLANILLA IN TAJO_PROYECTO.TAJO_PLANILLAS_TB.ID_PLANILLA%TYPE
) IS
    V_ID_PLANILLA TAJO_PROYECTO.TAJO_PLANILLAS_TB.ID_PLANILLA%TYPE;
BEGIN
    
    SELECT ID_PLANILLA INTO V_ID_PLANILLA 
    FROM TAJO_PROYECTO.TAJO_PLANILLAS_TB 
    WHERE ID_PLANILLA = P_ID_PLANILLA;

    UPDATE TAJO_PROYECTO.TAJO_PLANILLAS_TB
    SET ID_ESTADO = 2
    WHERE ID_PLANILLA = P_ID_PLANILLA;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('PLANILLA DESACTIVADA (BORRADO LOGICO)');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA PLANILLA NO EXISTE');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_PLANILLAS_ELIMINAR_SP;

-----PROCEDIMIENTOS DE LA TABLA DE PRODUCCION
PROCEDURE TAJO_PRODUCCION_INSERTAR_SP (
    P_ID_PRODUCCION IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_PRODUCCION%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.CANTIDAD%TYPE,
    P_FECHA_PRODUCCION IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.FECHA_PRODUCCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_PRODUCCION_TB (ID_PRODUCCION, ID_MATERIAL, CANTIDAD, FECHA_PRODUCCION, ID_ESTADO)
    VALUES (P_ID_PRODUCCION, P_ID_MATERIAL, P_CANTIDAD, P_FECHA_PRODUCCION, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE PRODUCCION INSERTADO CORRECTAMENTE');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE PRODUCCION YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS O CANTIDAD INCORRECTA');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_PRODUCCION_INSERTAR_SP;

-- MODIFICAR PRODUCCION
PROCEDURE TAJO_PRODUCCION_MODIFICAR_SP (
    P_ID_PRODUCCION IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_PRODUCCION%TYPE,
    P_ID_MATERIAL_NUEVO IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD_NUEVA IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.CANTIDAD%TYPE,
    P_FECHA_NUEVA IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.FECHA_PRODUCCION%TYPE,
    P_ID_ESTADO_NUEVO IN NUMBER
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_PRODUCCION_TB
    SET ID_MATERIAL = P_ID_MATERIAL_NUEVO,
        CANTIDAD = P_CANTIDAD_NUEVA,
        FECHA_PRODUCCION = P_FECHA_NUEVA,
        ID_ESTADO = P_ID_ESTADO_NUEVO
    WHERE ID_PRODUCCION = P_ID_PRODUCCION;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE PRODUCCION MODIFICADO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL REGISTRO DE PRODUCCION NO EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_PRODUCCION_MODIFICAR_SP;


-- ELIMINAR PRODUCCION (BORRADO LOGICO)
PROCEDURE TAJO_PRODUCCION_ELIMINAR_SP (
    P_ID_PRODUCCION IN TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_PRODUCCION%TYPE
) IS
    V_ID_PRODUCCION TAJO_PROYECTO.TAJO_PRODUCCION_TB.ID_PRODUCCION%TYPE;
BEGIN
    SELECT ID_PRODUCCION INTO V_ID_PRODUCCION 
    FROM TAJO_PROYECTO.TAJO_PRODUCCION_TB 
    WHERE ID_PRODUCCION = P_ID_PRODUCCION;

    UPDATE TAJO_PROYECTO.TAJO_PRODUCCION_TB
    SET ID_ESTADO = 2
    WHERE ID_PRODUCCION = P_ID_PRODUCCION;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('REGISTRO DE PRODUCCION DESACTIVADO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL REGISTRO DE PRODUCCION NO EXISTE');
    WHEN INVALID_NUMBER OR VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: TIPO DE DATO NO VALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_PRODUCCION_ELIMINAR_SP;

----PROCEDIMIENTOS DE LA TABLA DE ROLES
PROCEDURE TAJO_ROLES_INSERTAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_ROLES_TB.IDENTIFICACION%TYPE,
    P_ID_ROL IN TAJO_PROYECTO.TAJO_ROLES_TB.ID_ROL%TYPE,
    P_NOMBRE_ROL IN TAJO_PROYECTO.TAJO_ROLES_TB.NOMBRE_ROL%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_ROLES_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_ROLES_TB (IDENTIFICACION, ID_ROL, NOMBRE_ROL, ID_ESTADO)
    VALUES (P_IDENTIFICACION, P_ID_ROL, P_NOMBRE_ROL, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('ROL INSERTADO CORRECTAMENTE');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA IDENTIFICACION O EL ID DE ROL YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INCORRECTO EN ROLES');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_ROLES_INSERTAR_SP;

-- MODIFICAR ROL
PROCEDURE TAJO_ROLES_MODIFICAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_ROLES_TB.IDENTIFICACION%TYPE,
    P_NOMBRE_ROL_NUEVO IN TAJO_PROYECTO.TAJO_ROLES_TB.NOMBRE_ROL%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_ROLES_TB
    SET NOMBRE_ROL = P_NOMBRE_ROL_NUEVO
    WHERE IDENTIFICACION = P_IDENTIFICACION;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('NOMBRE DEL ROL MODIFICADO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRO EL ROL CON ESA IDENTIFICACION');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: VALOR INVALIDO PARA EL NOMBRE DEL ROL');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_ROLES_MODIFICAR_SP;


-- ELIMINAR ROL (BORRADO LOGICO)
PROCEDURE TAJO_ROLES_ELIMINAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_ROLES_TB.IDENTIFICACION%TYPE,
    P_ID_ROL IN TAJO_PROYECTO.TAJO_ROLES_TB.ID_ROL%TYPE
) IS
    V_ID_VALIDAR TAJO_PROYECTO.TAJO_ROLES_TB.IDENTIFICACION%TYPE;
BEGIN
    SELECT IDENTIFICACION INTO V_ID_VALIDAR 
    FROM TAJO_PROYECTO.TAJO_ROLES_TB 
    WHERE IDENTIFICACION = P_IDENTIFICACION 
      AND ID_ROL = P_ID_ROL;


    UPDATE TAJO_PROYECTO.TAJO_ROLES_TB
    SET ID_ESTADO = 2
    WHERE IDENTIFICACION = P_IDENTIFICACION 
      AND ID_ROL = P_ID_ROL;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('ROL DESACTIVADO EXITOSAMENTE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRO UN ROL QUE COINCIDA CON AMBOS PARAMETROS');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: PARAMETROS DE ENTRADA NO VALIDOS');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_ROLES_ELIMINAR_SP;

----PROCEDIMIENTOS DE LA TABLA DE TELFONOS
PROCEDURE TAJO_TELEFONOS_INSERTAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.IDENTIFICACION%TYPE,
    P_TELEFONO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.TELEFONO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_TELEFONOS_TB (IDENTIFICACION, TELEFONO, ID_ESTADO)
    VALUES (P_IDENTIFICACION, P_TELEFONO, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('TELEFONO REGISTRADO CORRECTAMENTE');
    
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL TELEFONO YA SE ENCUENTRA REGISTRADO');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE TELEFONO O IDENTIFICACION INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TELEFONOS_INSERTAR_SP;
-----
PROCEDURE TAJO_TELEFONOS_MODIFICAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.IDENTIFICACION%TYPE,
    P_TELEFONO_VIEJO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.TELEFONO%TYPE,
    P_TELEFONO_NUEVO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.TELEFONO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_TELEFONOS_TB
    SET TELEFONO = P_TELEFONO_NUEVO
    WHERE IDENTIFICACION = P_IDENTIFICACION 
      AND TELEFONO = P_TELEFONO_VIEJO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('TELEFONO ACTUALIZADO EXITOSAMENTE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRO EL REGISTRO PARA MODIFICAR');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS DATOS INGRESADOS NO SON VALIDOS');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TELEFONOS_MODIFICAR_SP;


-- ELIMINAR TELEFONO (BORRADO LOGICO)
PROCEDURE TAJO_TELEFONOS_ELIMINAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.IDENTIFICACION%TYPE,
    P_TELEFONO IN TAJO_PROYECTO.TAJO_TELEFONOS_TB.TELEFONO%TYPE
) IS
    V_VALIDAR TAJO_PROYECTO.TAJO_TELEFONOS_TB.IDENTIFICACION%TYPE;
BEGIN
    SELECT IDENTIFICACION INTO V_VALIDAR 
    FROM TAJO_PROYECTO.TAJO_TELEFONOS_TB 
    WHERE IDENTIFICACION = P_IDENTIFICACION 
      AND TELEFONO = P_TELEFONO;

    UPDATE TAJO_PROYECTO.TAJO_TELEFONOS_TB
    SET ID_ESTADO = 2
    WHERE IDENTIFICACION = P_IDENTIFICACION 
      AND TELEFONO = P_TELEFONO;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('TELEFONO DESACTIVADO CORRECTAMENTE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO EXISTE EL TELEFONO PARA ESA IDENTIFICACION');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: DATOS DE ENTRADA ERRONEOS');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TELEFONOS_ELIMINAR_SP;

-----PROCEDIMIENTOS PARA LA TABLA DE TIPO DE CLIENTES
PROCEDURE TAJO_TIPO_CLIENTE_INSERTAR_SP (
    P_ID_TIPO_CLIENTE IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.ID_TIPO_CLIENTE%TYPE,
    P_NOMBRE_TIPO IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.NOMBRE_TIPO_CLIENTE%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB (ID_TIPO_CLIENTE, NOMBRE_TIPO_CLIENTE, ID_ESTADO)
    VALUES (P_ID_TIPO_CLIENTE, P_NOMBRE_TIPO, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('NUEVO TIPO DE CLIENTE REGISTRADO');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE TIPO DE CLIENTE YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INVALIDO PARA EL TIPO DE CLIENTE');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TIPO_CLIENTE_INSERTAR_SP;


-- MODIFICAR TIPO DE CLIENTE
PROCEDURE TAJO_TIPO_CLIENTE_MODIFICAR_SP (
    P_ID_TIPO_CLIENTE IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.ID_TIPO_CLIENTE%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.NOMBRE_TIPO_CLIENTE%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB
    SET NOMBRE_TIPO_CLIENTE = P_NOMBRE_NUEVO
    WHERE ID_TIPO_CLIENTE = P_ID_TIPO_CLIENTE;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('NOMBRE DEL TIPO DE CLIENTE ACTUALIZADO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRO EL TIPO DE CLIENTE ESPECIFICADO');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL NOMBRE INGRESADO ES INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TIPO_CLIENTE_MODIFICAR_SP;

-- ELIMINAR TIPO DE CLIENTE (BORRADO LOGICO)
PROCEDURE TAJO_TIPO_CLIENTE_ELIMINAR_SP (
    P_ID_TIPO_CLIENTE IN TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.ID_TIPO_CLIENTE%TYPE
) IS
    V_ID_VALIDAR TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB.ID_TIPO_CLIENTE%TYPE;
BEGIN
    SELECT ID_TIPO_CLIENTE INTO V_ID_VALIDAR 
    FROM TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB 
    WHERE ID_TIPO_CLIENTE = P_ID_TIPO_CLIENTE;

    UPDATE TAJO_PROYECTO.TAJO_TIPO_CLIENTE_TB
    SET ID_ESTADO = 2
    WHERE ID_TIPO_CLIENTE = P_ID_TIPO_CLIENTE;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('TIPO DE CLIENTE DESACTIVADO EXITOSAMENTE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL TIPO DE CLIENTE NO EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: PARAMETRO DE ID NO VALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TIPO_CLIENTE_ELIMINAR_SP;

----PROCEDIMIENTOS PARA LA TABLA DE TIPO_MAQUINARIA
PROCEDURE TAJO_TIPO_MAQUINARIA_INSERTAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.PLACA%TYPE,
    P_ID_TIPO IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.ID_TIPO_MAQUINARIA%TYPE,
    P_DESCRIPCION IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB (PLACA, ID_TIPO_MAQUINARIA, DESCRIPCION, ID_ESTADO
    )
    VALUES (P_PLACA, P_ID_TIPO, P_DESCRIPCION, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MAQUINARIA REGISTRADA CORRECTAMENTE');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA PLACA O EL ID DE MAQUINARIA YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INVALIDO PARA MAQUINARIA');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TIPO_MAQUINARIA_INSERTAR_SP;

-- MODIFICAR TIPO MAQUINARIA
PROCEDURE TAJO_TIPO_MAQUINARIA_MODIFICAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.PLACA%TYPE,
    P_DESCRIPCION_NUEVA IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.DESCRIPCION%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB
    SET DESCRIPCION = P_DESCRIPCION_NUEVA
    WHERE PLACA = P_PLACA;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DESCRIPCION DE MAQUINARIA ACTUALIZADA');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRO MAQUINARIA CON ESA PLACA');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL VALOR DE DESCRIPCION NO ES VALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TIPO_MAQUINARIA_MODIFICAR_SP;

-- ELIMINAR TIPO MAQUINARIA (BORRADO LOGICO)
PROCEDURE TAJO_TIPO_MAQUINARIA_ELIMINAR_SP (
    P_PLACA IN TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.PLACA%TYPE
) IS
    V_PLACA_VALIDAR TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB.PLACA%TYPE;
BEGIN
    -- Validamos existencia antes de proceder
    SELECT PLACA INTO V_PLACA_VALIDAR 
    FROM TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB 
    WHERE PLACA = P_PLACA;

    UPDATE TAJO_PROYECTO.TAJO_TIPO_MAQUINARIA_TB
    SET ID_ESTADO = 2
    WHERE PLACA = P_PLACA;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MAQUINARIA DESACTIVADA EXITOSAMENTE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA PLACA ESPECIFICADA NO EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: PARAMETRO DE PLACA NO VALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TIPO_MAQUINARIA_ELIMINAR_SP;

----PROCEDIMIENTOS DE LA TABLA DE TIPO_MOVIMIENTO_INVENTARIO
PROCEDURE TAJO_TIPO_MOVIMIENTO_INVENTARIO_INSERTAR_SP (
    P_ID_TIPO_MOVIMIENTO IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO_INVENTARIO%TYPE,
    P_DESCRIPCION IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.DESCRIPCION%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB (ID_TIPO_MOVIMIENTO_INVENTARIO, DESCRIPCION, ID_ESTADO)
    VALUES (P_ID_TIPO_MOVIMIENTO, P_DESCRIPCION, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('TIPO DE MOVIMIENTO REGISTRADO CON EXITO');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE MOVIMIENTO YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO INCORRECTO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TIPO_MOVIMIENTO_INVENTARIO_INSERTAR_SP;

-- MODIFICAR TIPO MOVIMIENTO
PROCEDURE TAJO_TIPO_MOVIMIENTO_INVENTARIO_MODIFICAR_SP (
    P_ID_TIPO_MOVIMIENTO IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO_INVENTARIO%TYPE,
    P_DESCRIPCION_NUEVA IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.DESCRIPCION%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB
    SET DESCRIPCION = P_DESCRIPCION_NUEVA
    WHERE ID_TIPO_MOVIMIENTO_INVENTARIO = P_ID_TIPO_MOVIMIENTO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DESCRIPCION DE MOVIMIENTO ACTUALIZADA');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRO EL ID DE MOVIMIENTO');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: VALOR DE ENTRADA INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TIPO_MOVIMIENTO_INVENTARIO_MODIFICAR_SP;

-- ELIMINAR TIPO MOVIMIENTO (BORRADO LOGICO)
PROCEDURE TAJO_TIPO_MOVIMIENTO_INVENTARIO_ELIMINAR_SP (
    P_ID_TIPO_MOVIMIENTO IN TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO_INVENTARIO%TYPE
) IS
    V_ID_VALIDAR TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB.ID_TIPO_MOVIMIENTO_INVENTARIO%TYPE;
BEGIN
    -- Validamos existencia antes de desactivar
    SELECT ID_TIPO_MOVIMIENTO_INVENTARIO INTO V_ID_VALIDAR 
    FROM TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB 
    WHERE ID_TIPO_MOVIMIENTO_INVENTARIO = P_ID_TIPO_MOVIMIENTO;

    UPDATE TAJO_PROYECTO.TAJO_TIPO_MOVIMIENTO_INVENTARIO_TB
    SET ID_ESTADO = 2
    WHERE ID_TIPO_MOVIMIENTO_INVENTARIO = P_ID_TIPO_MOVIMIENTO;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('TIPO DE MOVIMIENTO DESACTIVADO (LOGICO)');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE MOVIMIENTO NO EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: PARAMETRO NO VALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TIPO_MOVIMIENTO_INVENTARIO_ELIMINAR_SP;

----PROCEDIMIENTOS DE LA TABLA DE TURNOS
PROCEDURE TAJO_TURNOS_INSERTAR_SP (
    P_ID_TURNO IN TAJO_PROYECTO.TAJO_TURNOS_TB.ID_TURNO%TYPE,
    P_NOMBRE_TURNO IN TAJO_PROYECTO.TAJO_TURNOS_TB.NOMBRE_TURNO%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_TURNOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_TURNOS_TB (ID_TURNO, NOMBRE_TURNO, ID_ESTADO)
    VALUES (P_ID_TURNO, P_NOMBRE_TURNO, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('TURNO REGISTRADO CORRECTAMENTE');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE TURNO YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATO INCORRECTO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TURNOS_INSERTAR_SP;

-- MODIFICAR TURNO
PROCEDURE TAJO_TURNOS_MODIFICAR_SP (
    P_ID_TURNO IN TAJO_PROYECTO.TAJO_TURNOS_TB.ID_TURNO%TYPE,
    P_NOMBRE_NUEVO IN TAJO_PROYECTO.TAJO_TURNOS_TB.NOMBRE_TURNO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_TURNOS_TB
    SET NOMBRE_TURNO = P_NOMBRE_NUEVO
    WHERE ID_TURNO = P_ID_TURNO;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('NOMBRE DEL TURNO ACTUALIZADO');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL TURNO NO EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: VALOR INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TURNOS_MODIFICAR_SP;

-- ELIMINAR TURNO (BORRADO LOGICO)
PROCEDURE TAJO_TURNOS_ELIMINAR_SP (
    P_ID_TURNO IN TAJO_PROYECTO.TAJO_TURNOS_TB.ID_TURNO%TYPE
) IS
    V_ID_VALIDAR TAJO_PROYECTO.TAJO_TURNOS_TB.ID_TURNO%TYPE;
BEGIN
    SELECT ID_TURNO INTO V_ID_VALIDAR 
    FROM TAJO_PROYECTO.TAJO_TURNOS_TB 
    WHERE ID_TURNO = P_ID_TURNO;

    UPDATE TAJO_PROYECTO.TAJO_TURNOS_TB
    SET ID_ESTADO = 2
    WHERE ID_TURNO = P_ID_TURNO;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('TURNO DESACTIVADO EXITOSAMENTE');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL TURNO NO EXISTE');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_TURNOS_ELIMINAR_SP;

----PROCEDIMIENTOS DE LA TABLA DE USUSARIOS
PROCEDURE TAJO_USUARIOS_INSERTAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_USUARIOS_TB.IDENTIFICACION%TYPE,
    P_NOMBRE         IN TAJO_PROYECTO.TAJO_USUARIOS_TB.NOMBRE_USUARIO%TYPE,
    P_APELLIDO_PATERNO IN TAJO_PROYECTO.TAJO_USUARIOS_TB.APELLIDO_PATERNO%TYPE,
    P_APELLIDO_MATERNO IN TAJO_PROYECTO.TAJO_USUARIOS_TB.APELLIDO_MATERNO%TYPE,
    P_EDAD           IN TAJO_PROYECTO.TAJO_USUARIOS_TB.EDAD%TYPE,
    P_FECHA_INGRESO  IN TAJO_PROYECTO.TAJO_USUARIOS_TB.FECHA_INGRESO%TYPE,
    P_ID_TURNO       IN TAJO_PROYECTO.TAJO_USUARIOS_TB.ID_TURNO%TYPE,
    P_PLACA          IN TAJO_PROYECTO.TAJO_USUARIOS_TB.PLACA%TYPE,
    P_ID_ESTADO      IN TAJO_PROYECTO.TAJO_USUARIOS_TB.ID_ESTADO%TYPE,
    P_CONTRASENA     IN TAJO_PROYECTO.TAJO_USUARIOS_TB.CONTRASENA%TYPE -- Parámetro nuevo
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_USUARIOS_TB (IDENTIFICACION, NOMBRE_USUARIO, APELLIDO_PATERNO, APELLIDO_MATERNO, EDAD, 
    FECHA_INGRESO, ID_TURNO, PLACA, ID_ESTADO, 
        CONTRASENA)
    VALUES (P_IDENTIFICACION, P_NOMBRE, P_APELLIDO_PATERNO, P_APELLIDO_MATERNO, P_EDAD, P_FECHA_INGRESO, P_ID_TURNO, P_PLACA, P_ID_ESTADO, P_CONTRASENA);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('USUARIO REGISTRADO EXITOSAMENTE');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA IDENTIFICACION YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS VALORES INGRESADOS NO SON VALIDOS');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END TAJO_USUARIOS_INSERTAR_SP;
----
PROCEDURE TAJO_USUARIOS_MODIFICAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_USUARIOS_TB.IDENTIFICACION%TYPE,
    P_NOMBRE         IN TAJO_PROYECTO.TAJO_USUARIOS_TB.NOMBRE_USUARIO%TYPE,
    P_APE_PATERNO    IN TAJO_PROYECTO.TAJO_USUARIOS_TB.APELLIDO_PATERNO%TYPE,
    P_APE_MATERNO    IN TAJO_PROYECTO.TAJO_USUARIOS_TB.APELLIDO_MATERNO%TYPE,
    P_EDAD           IN TAJO_PROYECTO.TAJO_USUARIOS_TB.EDAD%TYPE,
    P_ID_TURNO_NUEVO IN TAJO_PROYECTO.TAJO_USUARIOS_TB.ID_TURNO%TYPE,
    P_PLACA_NUEVA    IN TAJO_PROYECTO.TAJO_USUARIOS_TB.PLACA%TYPE,
    P_ID_ESTADO_NUEVO IN TAJO_PROYECTO.TAJO_USUARIOS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_USUARIOS_TB
    SET NOMBRE_USUARIO = P_NOMBRE,
        APELLIDO_PATERNO = P_APE_PATERNO,
        APELLIDO_MATERNO = P_APE_MATERNO,
        EDAD = P_EDAD,
        ID_TURNO = P_ID_TURNO_NUEVO,
        PLACA = P_PLACA_NUEVA,
        ID_ESTADO = P_ID_ESTADO_NUEVO
    WHERE IDENTIFICACION = P_IDENTIFICACION;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('DATOS DE USUARIO ACTUALIZADOS');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRO EL USUARIO');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LOS VALORES INGRESADOS NO SON VALIDOS');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM);
END TAJO_USUARIOS_MODIFICAR_SP;

-- ELIMINAR USUARIO (BORRADO LOGICO)
PROCEDURE TAJO_USUARIOS_ELIMINAR_SP (
    P_IDENTIFICACION IN TAJO_PROYECTO.TAJO_USUARIOS_TB.IDENTIFICACION%TYPE
) IS
    V_ID_VALIDAR TAJO_PROYECTO.TAJO_USUARIOS_TB.IDENTIFICACION%TYPE;
BEGIN
    SELECT IDENTIFICACION INTO V_ID_VALIDAR 
    FROM TAJO_PROYECTO.TAJO_USUARIOS_TB 
    WHERE IDENTIFICACION = P_IDENTIFICACION;

    UPDATE TAJO_PROYECTO.TAJO_USUARIOS_TB
    SET ID_ESTADO = 2
    WHERE IDENTIFICACION = P_IDENTIFICACION;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('USUARIO DESACTIVADO (LOGICO)');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL USUARIO NO EXISTE');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_USUARIOS_ELIMINAR_SP;

----PROCEDIMIENTOS DE LA TABLA DE VENTAS
PROCEDURE TAJO_VENTAS_INSERTAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_VENTA%TYPE,
    P_CEDULA IN TAJO_PROYECTO.TAJO_VENTAS_TB.CEDULA%TYPE,
    P_ID_MATERIAL IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_MATERIAL%TYPE, -- NUEVO FK
    P_CANTIDAD IN TAJO_PROYECTO.TAJO_VENTAS_TB.CANTIDAD_VENTA%TYPE,
    P_PRECIO IN TAJO_PROYECTO.TAJO_VENTAS_TB.PRECIO%TYPE,
    P_FECHA IN TAJO_PROYECTO.TAJO_VENTAS_TB.FECHA_VENTA%TYPE,
    P_ID_ESTADO IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_ESTADO%TYPE
) IS
BEGIN
    INSERT INTO TAJO_PROYECTO.TAJO_VENTAS_TB (ID_VENTA, CEDULA, ID_MATERIAL, CANTIDAD_VENTA, PRECIO, FECHA_VENTA, ID_ESTADO)
    VALUES (P_ID_VENTA, P_CEDULA, P_ID_MATERIAL, P_CANTIDAD, P_PRECIO, P_FECHA, P_ID_ESTADO);
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('VENTA REGISTRADA CON MATERIAL ESPECIFICADO');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: EL ID DE VENTA YA EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_VENTAS_INSERTAR_SP;


-- MODIFICAR VENTA (CAMBIO DE MATERIAL O CANTIDAD O PRECIO)
PROCEDURE TAJO_VENTAS_MODIFICAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_VENTA%TYPE,
    P_ID_MATERIAL_NUEVO IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_MATERIAL%TYPE,
    P_CANTIDAD_NUEVA IN TAJO_PROYECTO.TAJO_VENTAS_TB.CANTIDAD_VENTA%TYPE,
    P_PRECIO_NUEVO IN TAJO_PROYECTO.TAJO_VENTAS_TB.PRECIO%TYPE
) IS
BEGIN
    UPDATE TAJO_PROYECTO.TAJO_VENTAS_TB
    SET ID_MATERIAL = P_ID_MATERIAL_NUEVO,
        CANTIDAD_VENTA = P_CANTIDAD_NUEVA,
        PRECIO = P_PRECIO_NUEVO
    WHERE ID_VENTA = P_ID_VENTA;

    IF SQL%NOTFOUND THEN
        RAISE NO_DATA_FOUND;
    END IF;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('MATERIAL Y CANTIDAD ACTUALIZADOS EN LA VENTA');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: NO SE ENCONTRO LA VENTA');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_VENTAS_MODIFICAR_SP;

-- ELIMINAR VENTA (BORRADO LOGICO)
PROCEDURE TAJO_VENTAS_ELIMINAR_SP (
    P_ID_VENTA IN TAJO_PROYECTO.TAJO_VENTAS_TB.ID_VENTA%TYPE
) IS
    V_ID_VALIDAR TAJO_PROYECTO.TAJO_VENTAS_TB.ID_VENTA%TYPE;
BEGIN
    SELECT ID_VENTA INTO V_ID_VALIDAR 
    FROM TAJO_PROYECTO.TAJO_VENTAS_TB 
    WHERE ID_VENTA = P_ID_VENTA;

    UPDATE TAJO_PROYECTO.TAJO_VENTAS_TB
    SET ID_ESTADO = 2
    WHERE ID_VENTA = P_ID_VENTA;
    
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('VENTA ANULADA (ESTADO INACTIVO)');
EXCEPTION
    WHEN NO_DATA_FOUND THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: LA VENTA NO EXISTE');
    WHEN VALUE_ERROR THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: FORMATO DE DATOS INVALIDO');
    WHEN OTHERS THEN ROLLBACK;
        DBMS_OUTPUT.PUT_LINE('ERROR: '||SQLERRM);
END TAJO_VENTAS_ELIMINAR_SP;





END TAJO_PROYECTO_FINAL_PKG;